import assert from "node:assert/strict";
import test from "node:test";
import { findProgramAddress } from "../src/solana-pda.js";
import { acquireTransferHookAccountData, decodeTransferHookExtraAccountMetaList, resolveTransferHookAccountMetas } from "../src/transfer-hook-evidence.js";

const address = (fill) => { const alphabet = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"; let value = 0n, output = ""; for (const byte of Buffer.alloc(32, fill)) value = value * 256n + BigInt(byte); while (value) { output = alphabet[Number(value % 58n)] + output; value /= 58n; } return output; };
function base58Bytes(value) { const alphabet = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz", indexes = new Map([...alphabet].map((character, index) => [character, index])); let number = 0n; for (const character of value) number = number * 58n + BigInt(indexes.get(character)); const bytes = []; while (number) { bytes.unshift(Number(number & 255n)); number >>= 8n; } while (bytes.length < 32) bytes.unshift(0); return bytes; }
function list(entries) { const data = Buffer.alloc(16 + entries.length * 35); Buffer.from([105, 37, 101, 197, 75, 251, 102, 26]).copy(data); data.writeUInt32LE(4 + entries.length * 35, 8); data.writeUInt32LE(entries.length, 12); entries.forEach((entry, index) => { const offset = 16 + index * 35; data[offset] = entry.discriminator; entry.config.copy(data, offset + 1); data[offset + 33] = entry.signer ? 1 : 0; data[offset + 34] = entry.writable ? 1 : 0; }); return decodeTransferHookExtraAccountMetaList(data.toString("hex")); }

test("transfer-hook metadata resolves static, hook PDA, and prior-account external PDA forms", () => {
  const source = address(1), mint = address(2), destination = address(3), authority = address(4), validationAccount = address(5), hookProgramId = address(6), externalProgram = address(7), literal = Buffer.from("vault"), amount = Buffer.alloc(8), hookConfig = Buffer.alloc(32), externalConfig = Buffer.alloc(32); amount.writeBigUInt64LE(42n); hookConfig[0] = 1; hookConfig[1] = literal.length; literal.copy(hookConfig, 2); hookConfig[2 + literal.length] = 3; hookConfig[3 + literal.length] = 1; hookConfig[4 + literal.length] = 2; hookConfig[5 + literal.length] = 8; hookConfig[6 + literal.length] = 8; externalConfig[0] = 3; externalConfig[1] = 0;
  const metaList = list([{ discriminator: 0, config: Buffer.alloc(32, 7), writable: false }, { discriminator: 1, config: hookConfig, writable: true }, { discriminator: 133, config: externalConfig, writable: true }]), resolved = resolveTransferHookAccountMetas({ metaList, hookProgramId, validationAccount, source, mint, destination, authority, amountRaw: "42" });
  assert.deepEqual(resolved.accounts, [{ address: externalProgram, signer: false, writable: false }, { address: findProgramAddress(hookProgramId, [literal, Buffer.alloc(32, 2), amount]).address, signer: false, writable: true }, { address: findProgramAddress(externalProgram, [Buffer.alloc(32, 1)]).address, signer: false, writable: true }]);
});

test("transfer-hook metadata rejects source-account-derived and malformed seed forms", () => {
  const common = { hookProgramId: address(6), validationAccount: address(5), source: address(1), mint: address(2), destination: address(3), authority: address(4), amountRaw: "42" }, accountData = Buffer.alloc(32); accountData[0] = 4; accountData[1] = 0; accountData[2] = 0; accountData[3] = 1;
  assert.throws(() => resolveTransferHookAccountMetas({ ...common, metaList: list([{ discriminator: 1, config: accountData }]) }), /source-account evidence/); const bad = Buffer.alloc(16); Buffer.from([105, 37, 101, 197, 75, 251, 102, 26]).copy(bad); bad.writeUInt32LE(4, 8); bad.writeUInt32LE(65, 12); assert.throws(() => decodeTransferHookExtraAccountMetaList(bad.toString("hex")), /length/);
});

test("transfer-hook metadata resolves finalized account bytes and de-escalates privileges", () => {
  const source = address(1), mint = address(2), destination = address(3), authority = address(4), validationAccount = address(5), hookProgramId = address(6), embedded = address(8), sourceData = Buffer.alloc(80), destinationData = Buffer.alloc(24), pdaConfig = Buffer.alloc(32), pubkeyConfig = Buffer.alloc(32); Buffer.from(base58Bytes(embedded)).copy(sourceData, 7); Buffer.from([9, 8, 7, 6]).copy(destinationData, 11); pdaConfig.set([4, 2, 11, 4]); pubkeyConfig.set([2, 0, 7]);
  const metaList = list([{ discriminator: 1, config: pdaConfig, signer: true, writable: true }, { discriminator: 2, config: pubkeyConfig, signer: true, writable: true }, { discriminator: 0, config: Buffer.alloc(32, 1), signer: true, writable: true }]);
  const resolved = resolveTransferHookAccountMetas({ metaList, hookProgramId, validationAccount, source, mint, destination, authority, amountRaw: "42", accountData: { [source]: sourceData.toString("hex"), [destination]: { rawHex: destinationData.toString("hex") } } });
  assert.deepEqual(resolved.accounts, [{ address: findProgramAddress(hookProgramId, [Buffer.from([9, 8, 7, 6])]).address, signer: false, writable: true }, { address: embedded, signer: false, writable: true }, { address: source, signer: false, writable: true }]);
  const duplicateReadonly = list([{ discriminator: 0, config: Buffer.alloc(32, 2), signer: true, writable: true }]); assert.deepEqual(resolveTransferHookAccountMetas({ metaList: duplicateReadonly, hookProgramId, validationAccount, source, mint, destination, authority, amountRaw: "42" }).accounts, [{ address: mint, signer: false, writable: false }]);
  assert.throws(() => resolveTransferHookAccountMetas({ metaList, hookProgramId, validationAccount, source, mint, destination, authority, amountRaw: "42" }), /source-account evidence/);
});

test("transfer-hook source acquisition refetches dependencies at one finalized context", async () => {
  const source = address(1), mint = address(2), destination = address(3), authority = address(4), validationAccount = address(5), hookProgramId = address(6), firstData = Buffer.alloc(40), derivedData = Buffer.alloc(40), firstConfig = Buffer.alloc(32), secondConfig = Buffer.alloc(32); firstData.set([1, 2, 3], 4); derivedData.set([7, 8], 9); firstConfig.set([4, 0, 4, 3]); const derived = findProgramAddress(hookProgramId, [Buffer.from([1, 2, 3])]).address; secondConfig.set([4, 5, 9, 2]); const metaList = list([{ discriminator: 1, config: firstConfig }, { discriminator: 1, config: secondConfig }]), calls = [];
  const account = (owner, bytes) => ({ owner, data: [bytes.toString("base64"), "base64"] }), client = { call: async (_method, [addresses, config]) => { calls.push({ addresses, config }); return { context: { slot: 101 + calls.length }, value: addresses.map((addressValue) => account(address(9), addressValue === source ? firstData : derivedData)) }; } };
  const acquired = await acquireTransferHookAccountData(client, { metaList, hookProgramId, validationAccount, source, mint, destination, authority, amountRaw: "42" }, 100);
  assert.deepEqual(calls.map((call) => call.addresses), [[source], [source, derived]]); assert.deepEqual(calls.map((call) => call.config.minContextSlot), [100, 102]); assert.ok(calls.every((call) => call.config.commitment === "finalized" && call.config.encoding === "base64")); assert.equal(acquired.slot, 103); assert.deepEqual(Object.values(acquired.accountData).map((row) => row.slot), [103, 103]); assert.equal(acquired.resolved.accounts[0].address, derived); assert.equal(acquired.resolved.accounts[1].address, findProgramAddress(hookProgramId, [Buffer.from([7, 8])]).address);
  await assert.rejects(acquireTransferHookAccountData({ call: async () => ({ context: { slot: 101 }, value: [null] }) }, { metaList, hookProgramId, validationAccount, source, mint, destination, authority, amountRaw: "42" }, 100), /unavailable/);
});
