CREATE TABLE IF NOT EXISTS schema_migrations (version bigint PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tokens (chain text NOT NULL, mint text NOT NULL, decimals smallint, metadata jsonb NOT NULL DEFAULT '{}', authorities jsonb NOT NULL DEFAULT '{}', extensions jsonb NOT NULL DEFAULT '{}', source_slot bigint, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (chain, mint));
CREATE TABLE IF NOT EXISTS ingestion_checkpoints (consumer text PRIMARY KEY, chain text NOT NULL, genesis_hash text NOT NULL, slot bigint NOT NULL, cursor text, schema_version integer NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS candidates (chain text NOT NULL, mint text NOT NULL, score_version text NOT NULL, evidence_snapshot jsonb NOT NULL, score numeric, state text NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (chain, mint, score_version));
CREATE TABLE IF NOT EXISTS security_snapshots (id bigserial PRIMARY KEY, chain text NOT NULL, mint text NOT NULL, rule_version text NOT NULL, source_slot bigint, source_signature text, evidence jsonb NOT NULL, severity text NOT NULL, blocks_research boolean NOT NULL, blocks_entry boolean NOT NULL, blocks_exit boolean NOT NULL, observed_at timestamptz NOT NULL, expires_at timestamptz);
CREATE TABLE IF NOT EXISTS wallet_profiles (chain text NOT NULL, address text NOT NULL, profile_version text NOT NULL, evidence jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (chain, address, profile_version));
CREATE TABLE IF NOT EXISTS operational_jobs (id bigserial PRIMARY KEY, job_type text NOT NULL, payload jsonb NOT NULL, status text NOT NULL, attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_records (id bigserial PRIMARY KEY, actor text NOT NULL, action text NOT NULL, target text, evidence jsonb NOT NULL DEFAULT '{}', occurred_at timestamptz NOT NULL DEFAULT now());
INSERT INTO schema_migrations(version) VALUES (1) ON CONFLICT DO NOTHING;
