#!/usr/bin/env node
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { loadConfig, parseBoundedInteger } from "./config.js";
import { exportFinalizedBlocks, MAINNET_GENESIS_HASH, recordExporterFailure } from "./local-validator-exporter.js";
import { parseRetryAfterMs } from "./provider-retry.js";
import { readBoundedRpcJson } from "./rpc-response.js";

const PUBLIC_MAINNET = "https://api.mainnet.solana.com/";
const ALLOWED = { helius: new Set(["mainnet.helius-rpc.com"]), alchemy: new Set(["solana-mainnet.g.alchemy.com"]), "solana-public": new Set(["api.mainnet.solana.com", "api.mainnet-beta.solana.com"]) };
export function validateProviderUrl(name, value) { const url = new URL(value); if (url.protocol !== "https:" || !ALLOWED[name]?.has(url.hostname)) throw new Error(`invalid ${name} RPC endpoint`); return url.href; }

export class ExternalRpcPool {
  constructor(providers, { fetchImpl = fetch, timeoutMs = 20_000, maxResponseBytes = 67_108_864, failureThreshold = 3, cooldownMs = 30_000, genesisVerificationTtlMs = 300_000, now = () => Date.now() } = {}) { if (!Array.isArray(providers) || !providers.length) throw new Error("at least one RPC provider is required"); if (![timeoutMs, failureThreshold, cooldownMs, genesisVerificationTtlMs].every((value) => Number.isSafeInteger(value) && value >= 1)) throw new Error("external RPC timing and circuit settings must be positive integers"); if (!Number.isSafeInteger(maxResponseBytes) || maxResponseBytes < 1_024 || maxResponseBytes > 268_435_456) throw new Error("external RPC response limit is invalid"); const normalized = providers.map((row) => ({ name: row.name, endpoint: validateProviderUrl(row.name, row.endpoint) })); if (new Set(normalized.map((row) => row.name)).size !== normalized.length || new Set(normalized.map((row) => row.endpoint)).size !== normalized.length) throw new Error("external RPC providers must have unique names and endpoints"); this.providers = normalized.map((row) => ({ ...row, failures: 0, openUntil: 0, probeInFlight: false, calls: 0, errors: 0, verifiedGenesisHash: null, genesisVerifiedAt: null })); this.fetchImpl = fetchImpl; this.timeoutMs = timeoutMs; this.maxResponseBytes = maxResponseBytes; this.failureThreshold = failureThreshold; this.cooldownMs = cooldownMs; this.genesisVerificationTtlMs = genesisVerificationTtlMs; this.now = now; this.id = 0; this.lastProvider = null; }
  get provenanceSource() { return this.lastProvider ? `external-rpc-${this.lastProvider}` : "external-rpc-pool"; }
  async callProvider(provider, method, params = []) { provider.calls++; const requestId = ++this.id, response = await this.fetchImpl(provider.endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ jsonrpc: "2.0", id: requestId, method, params }), signal: AbortSignal.timeout(this.timeoutMs) }); if (!response.ok) { const retryable = [429, 503].includes(response.status), wait = retryable ? parseRetryAfterMs(response.headers?.get?.("retry-after"), this.now()) : null; if (retryable) provider.openUntil = this.now() + (wait ?? this.cooldownMs); throw new Error(`HTTP ${response.status}`); } const payload = await readBoundedRpcJson(response, this.maxResponseBytes), hasResult = Object.hasOwn(payload ?? {}, "result"), hasError = Object.hasOwn(payload ?? {}, "error"); if (payload?.jsonrpc !== "2.0" || payload.id !== requestId || hasResult === hasError) throw new Error("invalid JSON-RPC response envelope"); if (hasError) throw new Error(`RPC ${payload.error?.code ?? "unknown"}`); provider.failures = 0; provider.openUntil = 0; this.lastProvider = provider.name; return payload.result; }
  recordFailure(provider) { provider.errors++; provider.failures++; if (provider.openUntil <= this.now() && provider.failures >= this.failureThreshold) provider.openUntil = this.now() + this.cooldownMs; }
  hasCurrentGenesis(expected = MAINNET_GENESIS_HASH) { return this.providers.every((provider) => provider.verifiedGenesisHash === expected && Number.isSafeInteger(provider.genesisVerifiedAt) && this.now() - provider.genesisVerifiedAt >= 0 && this.now() - provider.genesisVerifiedAt <= this.genesisVerificationTtlMs); }
  async call(method, params = []) { if (method !== "getGenesisHash" && !this.hasCurrentGenesis()) throw new Error("external RPC providers require current provider-complete mainnet genesis verification"); const errors = []; for (const provider of this.providers) { if (provider.openUntil > this.now() || provider.probeInFlight) continue; const probe = provider.failures > 0; if (probe) provider.probeInFlight = true; try { return await this.callProvider(provider, method, params); } catch (error) { this.recordFailure(provider); errors.push(`${provider.name}:${error.name ?? "Error"}`); } finally { if (probe) provider.probeInFlight = false; } } throw new Error(`all external RPC providers unavailable (${errors.join(",") || "circuits_open"})`); }
  async assertGenesis(expected = MAINNET_GENESIS_HASH) { for (const provider of this.providers) { if (provider.verifiedGenesisHash === expected && Number.isSafeInteger(provider.genesisVerifiedAt) && this.now() - provider.genesisVerifiedAt >= 0 && this.now() - provider.genesisVerifiedAt <= this.genesisVerificationTtlMs) continue; if (provider.openUntil > this.now()) throw new Error(`external RPC genesis verification deferred for ${provider.name}`); let actual; try { actual = await this.callProvider(provider, "getGenesisHash"); } catch (error) { this.recordFailure(provider); throw new Error(`external RPC genesis verification failed for ${provider.name}`); } if (actual !== expected) { provider.verifiedGenesisHash = null; provider.genesisVerifiedAt = null; this.recordFailure(provider); throw new Error(`external RPC genesis mismatch for ${provider.name}: expected ${expected}, received ${actual}`); } provider.verifiedGenesisHash = actual; provider.genesisVerifiedAt = this.now(); } return expected; }
  telemetry() { const now = this.now(); return this.providers.map(({ endpoint, ...row }) => ({ ...row, circuitOpen: row.openUntil > now, circuitState: row.openUntil > now ? "open" : row.failures > 0 ? "half_open" : "closed", retryInMs: Math.max(0, row.openUntil - now) })); }
}

export function providerPoolFromEnv(env = process.env, options) { if (!env.HELIUS_RPC_URL || !env.ALCHEMY_RPC_URL) throw new Error("HELIUS_RPC_URL and ALCHEMY_RPC_URL are required"); return new ExternalRpcPool([{ name: "helius", endpoint: env.HELIUS_RPC_URL }, { name: "alchemy", endpoint: env.ALCHEMY_RPC_URL }], options); }
export function publicHealthClient(options) { return new ExternalRpcPool([{ name: "solana-public", endpoint: PUBLIC_MAINNET }], { ...options, failureThreshold: 1, cooldownMs: 60_000 }); }

async function main() {
  if (process.argv.includes("--health-public")) { const client = publicHealthClient(); const genesisHash = await client.assertGenesis(), health = await client.call("getHealth"); if (genesisHash !== MAINNET_GENESIS_HASH || health !== "ok") throw new Error("Solana public mainnet health check failed"); console.log(JSON.stringify({ provider: "solana-public", genesisHash, health })); return; }
  const config = loadConfig(), emergency = process.argv.includes("--emergency-public"), once = process.argv.includes("--once") || emergency; if (emergency && !process.argv.includes("--once")) console.warn("emergency public backfill is forced to one bounded cycle"); const client = emergency ? publicHealthClient() : providerPoolFromEnv(); const cursorFile = path.resolve(process.cwd(), process.env.EXPORTER_CURSOR_FILE || "data/external-exporter.cursor"), batchSize = parseBoundedInteger(process.env.EXPORTER_BATCH_SIZE, 8, 1, emergency ? 4 : 32), pollMs = parseBoundedInteger(process.env.EXPORTER_POLL_MS, 2_000, 100, 60_000);
  do { try { const result = await exportFinalizedBlocks({ client, inbox: config.inbox, cursorFile, statusFile: config.exporterStatusFile, batchSize, expectedGenesisHash: MAINNET_GENESIS_HASH }); console.log(JSON.stringify({ ...result, providers: client.telemetry() })); } catch (error) { await recordExporterFailure(config.exporterStatusFile, error, { source: client.provenanceSource }); throw error; } if (!once) await new Promise((resolve) => setTimeout(resolve, pollMs)); } while (!once);
}
const invokedFile = process.argv[1] ? path.resolve(process.argv[1]) : "";
if (fileURLToPath(import.meta.url).toLowerCase() === invokedFile.toLowerCase()) main().catch((error) => { console.error(error.message); process.exitCode = 1; });
