import crypto from "node:crypto";

const ED25519_P = (1n << 255n) - 19n;

export function encodeBase58(bytes) { const alphabet = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"; let value = 0n, output = ""; for (const byte of bytes) value = value * 256n + BigInt(byte); while (value) { output = alphabet[Number(value % 58n)] + output; value /= 58n; } for (const byte of bytes) { if (byte) break; output = `1${output}`; } return output || "1"; }
export function decodeBase58Address(value) { const alphabet = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz", indexes = new Map([...alphabet].map((character, index) => [character, index])); let number = 0n; if (typeof value !== "string" || !value) throw new Error("Solana address is invalid"); for (const character of value) { const digit = indexes.get(character); if (digit == null) throw new Error("Solana address is invalid"); number = number * 58n + BigInt(digit); } const bytes = []; while (number) { bytes.unshift(Number(number & 255n)); number >>= 8n; } for (const character of value) { if (character !== "1") break; bytes.unshift(0); } const decoded = Buffer.from(bytes); if (decoded.length !== 32 || encodeBase58(decoded) !== value) throw new Error("Solana address is invalid"); return decoded; }
function mod(value) { const result = value % ED25519_P; return result < 0n ? result + ED25519_P : result; }
function modPow(base, exponent) { let result = 1n, factor = mod(base), power = exponent; while (power) { if (power & 1n) result = mod(result * factor); factor = mod(factor * factor); power >>= 1n; } return result; }
function onEd25519Curve(encoded) { let y = 0n; for (let index = 31; index >= 0; index--) y = (y << 8n) | BigInt(encoded[index]); const sign = y >> 255n; y &= (1n << 255n) - 1n; if (y >= ED25519_P) return false; const y2 = mod(y * y), d = mod(-121665n * modPow(121666n, ED25519_P - 2n)), x2 = mod((y2 - 1n) * modPow(d * y2 + 1n, ED25519_P - 2n)); return x2 === 0n ? sign === 0n : modPow(x2, (ED25519_P - 1n) / 2n) === 1n; }

export function createProgramAddress(programId, seeds) { const program = decodeBase58Address(programId); if (!Array.isArray(seeds) || seeds.length > 16 || seeds.some((seed) => !Buffer.isBuffer(seed) || seed.length > 32) || seeds.reduce((total, seed) => total + seed.length, 0) > 512) throw new Error("Solana PDA seeds are invalid"); const digest = crypto.createHash("sha256").update(Buffer.concat([...seeds, program, Buffer.from("ProgramDerivedAddress")])).digest(); if (onEd25519Curve(digest)) throw new Error("Solana program address is on curve"); return encodeBase58(digest); }
export function findProgramAddress(programId, seeds) { if (!Array.isArray(seeds) || seeds.length > 15) throw new Error("Solana PDA seeds are invalid"); for (let bump = 255; bump >= 0; bump--) { try { return { address: createProgramAddress(programId, [...seeds, Buffer.from([bump])]), bump }; } catch (error) { if (error.message !== "Solana program address is on curve") throw error; } } throw new Error("unable to derive Solana program address"); }
