import fs from "node:fs/promises";
import path from "node:path";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import { loadConfig } from "./config.js";
import { IndexStore, isCanonicalAccountSnapshotEvidence } from "./store.js";
import { loadHolderExclusions } from "./holder-exclusions.js";
import { POOL_MINT_EVIDENCE_CONSTANTS, validateBoundPoolMintEvidence } from "./pool-mint-evidence.js";
import { ORCA_WHIRLPOOL_PROGRAM } from "./orca-pool-snapshot.js";

const CHAIN = "solana-mainnet";
const GENESIS_HASH = "5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d";
export const CANDLE_INTERVALS = [60, 300, 900, 3_600, 14_400, 86_400];

function sqlLiteral(value) { return `'${String(value).replaceAll("'", "''")}'`; }

export function compileWarehouseBatch(state, checkpoint = { lastSequence: 0 }) {
  const lastSequence = Number(checkpoint?.lastSequence ?? 0);
  if (!Number.isSafeInteger(lastSequence) || lastSequence < 0) throw new Error("invalid warehouse checkpoint");
  if (!Number.isSafeInteger(state?.eventSequence) || !Array.isArray(state?.events)) throw new Error("invalid index event state");
  let previous = null;
  for (const event of state.events) { if (!Number.isSafeInteger(event?.sequence) || (previous != null && event.sequence !== previous + 1) || typeof event.type !== "string" || !event.type) throw new Error(previous != null && event?.sequence > previous + 1 ? "warehouse event sequence gap" : "invalid non-monotonic index event sequence"); if (!Number.isSafeInteger(event.slot) || event.slot < 0 || (event.blockTime != null && (!Number.isSafeInteger(event.blockTime) || event.blockTime < 0)) || !["confirmed", "finalized"].includes(event.provenance?.commitment) || typeof event.blockhash !== "string" || !event.blockhash) throw new Error(`invalid warehouse event ${event.sequence}`); previous = event.sequence; }
  if (state.events.length && previous !== state.eventSequence) throw new Error("index event high-water mark mismatch");
  if (lastSequence > state.eventSequence) throw new Error("warehouse checkpoint is ahead of index");
  const oldest = state.events[0]?.sequence ?? state.eventSequence + 1;
  if (lastSequence < oldest - 1) throw new Error("warehouse checkpoint is older than retained replay history");
  const events = state.events.filter((event) => event.sequence > lastSequence);
  if (events.length && events[0].sequence !== lastSequence + 1) throw new Error("warehouse event sequence gap");
  const rows = events.map((event) => ({ chain: CHAIN, sequence: event.sequence, event_type: event.type, slot: event.slot, block_time: event.blockTime == null ? null : new Date(event.blockTime * 1_000).toISOString(), commitment: event.provenance?.commitment ?? "unknown", blockhash: event.blockhash ?? "", payload: JSON.stringify(event) }));
  return { fromSequence: lastSequence + 1, toSequence: events.at(-1)?.sequence ?? lastSequence, events: rows };
}

function factBase(row) {
  if (!Number.isSafeInteger(row?.slot) || row.slot < 0 || (row.blockTime != null && (!Number.isSafeInteger(row.blockTime) || row.blockTime < 0)) || typeof row.signature !== "string" || !row.signature || !["confirmed", "finalized"].includes(row.provenance?.commitment)) throw new Error("invalid canonical warehouse fact");
  return { chain: CHAIN, slot: row.slot, block_time: row.blockTime == null ? null : new Date(row.blockTime * 1_000).toISOString(), signature: row.signature, commitment: row.provenance.commitment };
}

export function compileWarehouseFacts(state, batch) {
  const slots = [...new Set(batch.events.map((event) => event.slot))].sort((a, b) => a - b), selected = (rows) => (rows ?? []).filter((row) => slots.includes(row.slot));
  const identities = new Set(), unique = (identity) => { if (identities.has(identity)) throw new Error(`duplicate canonical warehouse fact ${identity}`); identities.add(identity); };
  const instructions = selected(state.instructions).map((row) => { const base = factBase(row); if (!Number.isInteger(row.instructionIndex) || row.instructionIndex < 0 || (row.innerIndex != null && (!Number.isInteger(row.innerIndex) || row.innerIndex < 0)) || typeof row.eventId !== "string" || !row.eventId || typeof row.programId !== "string" || !row.programId || !Array.isArray(row.accounts) || !/^([0-9a-f]{64})$/.test(row.rawPayloadHash ?? "")) throw new Error("invalid canonical instruction fact"); unique(`instruction:${row.eventId}`); return { ...base, event_id: row.eventId, instruction_index: row.instructionIndex, inner_index: row.innerIndex, program_id: row.programId, protocol: row.protocol ?? null, registry_version: row.registryVersion, decoder_version: row.decoderVersion ?? null, parsed_type: row.parsedType ?? null, accounts: row.accounts, data: row.data ?? null, raw_payload_hash: row.rawPayloadHash, payload: JSON.stringify(row) }; });
  const swaps = selected(state.swaps).map((row) => { const base = factBase(row); if (typeof row.swapId !== "string" || !row.swapId || !Number.isInteger(row.eventIndex) || row.eventIndex < 0 || !row.pool || !row.protocol || !row.baseMint || !row.quoteMint || !row.inputMint || !row.outputMint || !/^\d+$/.test(row.inputAmountRaw ?? "") || !/^\d+$/.test(row.outputAmountRaw ?? "") || (row.tradeFeeRaw != null && !/^\d+$/.test(row.tradeFeeRaw)) || !/^([0-9a-f]{64})$/.test(row.rawPayloadHash ?? "")) throw new Error("invalid canonical swap fact"); unique(`swap:${row.swapId}`); return { ...base, swap_id: row.swapId, event_index: row.eventIndex, pool: row.pool, protocol: row.protocol, base_mint: row.baseMint, quote_mint: row.quoteMint, input_mint: row.inputMint, output_mint: row.outputMint, input_amount_raw: row.inputAmountRaw, output_amount_raw: row.outputAmountRaw, trade_fee_raw: row.tradeFeeRaw ?? null, decoder_version: row.decoderVersion ?? null, raw_payload_hash: row.rawPayloadHash, payload: JSON.stringify(row) }; });
  const balanceChanges = selected(state.balanceChanges).map((row) => { const base = factBase(row); if (!Number.isInteger(row.accountIndex) || row.accountIndex < 0 || !row.tokenAccount || !row.mint || !Number.isInteger(row.decimals) || row.decimals < 0 || row.decimals > 255 || !/^\d+$/.test(row.preAmountRaw ?? "") || !/^\d+$/.test(row.postAmountRaw ?? "") || typeof row.closed !== "boolean") throw new Error("invalid canonical balance fact"); unique(`balance:${row.signature}:${row.accountIndex}`); return { ...base, account_index: row.accountIndex, token_account: row.tokenAccount, owner: row.owner ?? null, program_id: row.programId ?? null, mint: row.mint, decimals: row.decimals, pre_amount_raw: row.preAmountRaw, post_amount_raw: row.postAmountRaw, closed: row.closed ? 1 : 0, payload: JSON.stringify(row) }; });
  const nativeTransfers = selected(state.nativeTransfers).map((row) => { const base = factBase(row), systemProgram = "11111111111111111111111111111111", stakeProgram = "Stake11111111111111111111111111111111111111", accountCreation = ["account_creation", "seeded_account_creation", "prefunded_account_creation"].includes(row.transferKind), seeded = ["seeded_account_creation", "seeded_transfer"].includes(row.transferKind); if (typeof row.transferId !== "string" || !row.transferId || !Number.isInteger(row.instructionIndex) || row.instructionIndex < 0 || (row.innerIndex != null && (!Number.isInteger(row.innerIndex) || row.innerIndex < 0)) || !((row.programId === systemProgram && ["transfer", "seeded_transfer", "account_creation", "seeded_account_creation", "prefunded_account_creation", "nonce_withdrawal"].includes(row.transferKind)) || (row.programId === stakeProgram && row.transferKind === "stake_withdrawal")) || typeof row.source !== "string" || !row.source || typeof row.destination !== "string" || !row.destination || !/^\d+$/.test(row.lamportsRaw ?? "") || BigInt(row.lamportsRaw) > 18_446_744_073_709_551_615n || (accountCreation && (!/^\d+$/.test(row.allocatedSpaceRaw ?? "") || BigInt(row.allocatedSpaceRaw) > 18_446_744_073_709_551_615n || typeof row.ownerProgram !== "string" || !row.ownerProgram)) || (!accountCreation && row.allocatedSpaceRaw != null) || (seeded && (typeof row.baseAddress !== "string" || !row.baseAddress || typeof row.seed !== "string" || row.seed.length > 32 || [...row.seed].some((character) => character.charCodeAt(0) > 0x7f) || typeof row.ownerProgram !== "string" || !row.ownerProgram)) || (!seeded && (row.baseAddress != null || row.seed != null)) || (!accountCreation && !seeded && row.ownerProgram != null) || ![3, 4, 5, 6, 7].includes(row.decoderVersion) || !/^([0-9a-f]{64})$/.test(row.rawPayloadHash ?? "")) throw new Error("invalid canonical native transfer fact"); unique(`native-transfer:${row.transferId}`); return { ...base, transfer_id: row.transferId, instruction_index: row.instructionIndex, inner_index: row.innerIndex, program_id: row.programId, transfer_kind: row.transferKind, source: row.source, destination: row.destination, lamports_raw: row.lamportsRaw, allocated_space_raw: row.allocatedSpaceRaw, owner_program: row.ownerProgram, base_address: row.baseAddress, seed: row.seed, decoder_version: row.decoderVersion, raw_payload_hash: row.rawPayloadHash, payload: JSON.stringify(row) }; });
  const deadLetters = (state.deadLetters ?? []).map((row) => { const observedAt = row.lastObservedAt ?? row.firstObservedAt, observed = Date.parse(observedAt ?? ""); if (typeof row.id !== "string" || !row.id || typeof row.filename !== "string" || !row.filename || (row.fingerprint != null && !/^[0-9a-f]{64}$/.test(row.fingerprint)) || typeof row.error !== "string" || !row.error || !Number.isSafeInteger(row.attempts) || row.attempts < 1 || !Number.isFinite(observed) || typeof row.resolved !== "boolean") throw new Error("invalid canonical dead-letter fact"); unique(`dead-letter:${row.id}`); return { chain: CHAIN, observed_at: new Date(observed).toISOString(), source: row.filename, identity: row.id, payload_hash: row.fingerprint ?? null, error: row.error, attempts: row.attempts, resolved: row.resolved ? 1 : 0, resolution: row.resolution ?? null, payload: JSON.stringify(row) }; });
  const candleProjection = compileWarehouseCandles(state, batch);
  return { slots, instructions, swaps, balanceChanges, nativeTransfers, deadLetters, ...candleProjection };
}

function candleAmounts(swap) {
  const base = swap.inputMint === swap.baseMint ? swap.inputAmountRaw : swap.outputMint === swap.baseMint ? swap.outputAmountRaw : null;
  const quote = swap.inputMint === swap.quoteMint ? swap.inputAmountRaw : swap.outputMint === swap.quoteMint ? swap.outputAmountRaw : null;
  if (!/^\d+$/.test(base ?? "") || !/^\d+$/.test(quote ?? "") || BigInt(base) === 0n) return null;
  return { base, quote };
}

export function compileWarehouseCandles(state, batch, intervals = CANDLE_INTERVALS) {
  if (!Array.isArray(intervals) || !intervals.length || intervals.some((value) => !Number.isSafeInteger(value) || value < 1) || new Set(intervals).size !== intervals.length) throw new Error("invalid warehouse candle intervals");
  const affected = new Map(), sourceSequence = (batch.events ?? []).reduce((value, event) => Math.max(value, event.sequence ?? -1), -1);
  if ((batch.events ?? []).length && (!Number.isSafeInteger(sourceSequence) || sourceSequence < 0)) throw new Error("invalid warehouse candle source sequence");
  for (const event of batch.events ?? []) {
    let payload; try { payload = JSON.parse(event.payload); } catch { throw new Error(`invalid warehouse candle event ${event.sequence}`); }
    for (const swap of [...(payload.swaps ?? []), ...(payload.revertedSwaps ?? [])]) {
      if (!swap?.pool || !Number.isSafeInteger(swap.blockTime) || swap.blockTime < 0) throw new Error("invalid warehouse candle source");
      for (const interval of intervals) { const bucket = Math.floor(swap.blockTime / interval) * interval, key = `${swap.pool}\u0000${interval}\u0000${bucket}`; affected.set(key, { pool: swap.pool, interval, bucket }); }
    }
  }
  const compare = (left, right) => { const a = BigInt(left.n) * BigInt(right.d), b = BigInt(right.n) * BigInt(left.d); return a === b ? 0 : a < b ? -1 : 1; };
  const candles = [];
  for (const key of [...affected.keys()].sort()) {
    const target = affected.get(key), candidates = (state.swaps ?? []).filter((swap) => swap.pool === target.pool && Number.isSafeInteger(swap.blockTime) && Math.floor(swap.blockTime / target.interval) * target.interval === target.bucket).sort((a, b) => a.blockTime - b.blockTime || a.slot - b.slot || a.eventIndex - b.eventIndex), row = { schema_version: 1, source_sequence: sourceSequence, chain: CHAIN, pool: target.pool, interval_seconds: target.interval, bucket_start: new Date(target.bucket * 1_000).toISOString(), base_mint: null, quote_mint: null, base_decimals: null, quote_decimals: null, open_numerator_raw: null, open_denominator_raw: null, high_numerator_raw: null, high_denominator_raw: null, low_numerator_raw: null, low_denominator_raw: null, close_numerator_raw: null, close_denominator_raw: null, base_volume_raw: 0n, quote_volume_raw: 0n, trades: 0, first_slot: null, last_slot: null, commitment: "finalized" };
    for (const swap of candidates) {
      const amounts = candleAmounts(swap); if (!amounts) continue;
      const pair = `${swap.baseMint}\u0000${swap.quoteMint}`; if (row.base_mint != null && pair !== `${row.base_mint}\u0000${row.quote_mint}`) throw new Error(`conflicting canonical candle pair ${target.pool}`);
      const price = { n: amounts.quote, d: amounts.base }; row.base_mint ??= swap.baseMint; row.quote_mint ??= swap.quoteMint; row.base_decimals ??= swap.baseDecimals ?? null; row.quote_decimals ??= swap.quoteDecimals ?? null;
      if (row.trades === 0) { row.open_numerator_raw = row.high_numerator_raw = row.low_numerator_raw = price.n; row.open_denominator_raw = row.high_denominator_raw = row.low_denominator_raw = price.d; row.first_slot = swap.slot; }
      if (compare(price, { n: row.high_numerator_raw, d: row.high_denominator_raw }) > 0) { row.high_numerator_raw = price.n; row.high_denominator_raw = price.d; }
      if (compare(price, { n: row.low_numerator_raw, d: row.low_denominator_raw }) < 0) { row.low_numerator_raw = price.n; row.low_denominator_raw = price.d; }
      row.close_numerator_raw = price.n; row.close_denominator_raw = price.d; row.base_volume_raw += BigInt(amounts.base); row.quote_volume_raw += BigInt(amounts.quote); row.trades++; row.last_slot = swap.slot; if (swap.provenance?.commitment !== "finalized") row.commitment = "confirmed";
    }
    if (row.trades) candles.push({ ...row, base_volume_raw: row.base_volume_raw.toString(), quote_volume_raw: row.quote_volume_raw.toString() });
  }
  return { candleKeys: [...affected.values()].sort((a, b) => a.pool.localeCompare(b.pool) || a.interval - b.interval || a.bucket - b.bucket), candles };
}

export function checkpointSql(sequence) {
  if (!Number.isSafeInteger(sequence) || sequence < 0) throw new Error("invalid warehouse sequence");
  return `INSERT INTO ingestion_checkpoints (consumer, chain, genesis_hash, slot, cursor, schema_version) VALUES ('warehouse-canonical-events', 'solana', ${sqlLiteral(GENESIS_HASH)}, ${sequence}, ${sqlLiteral(String(sequence))}, 1) ON CONFLICT (consumer) DO UPDATE SET chain = EXCLUDED.chain, genesis_hash = EXCLUDED.genesis_hash, slot = EXCLUDED.slot, cursor = EXCLUDED.cursor, schema_version = EXCLUDED.schema_version, updated_at = now();\n`;
}

function jsonbLiteral(value) { return `${sqlLiteral(JSON.stringify(value))}::jsonb`; }

function respCommand(parts) { const chunks = [Buffer.from(`*${parts.length}\r\n`)]; for (const part of parts) { const value = Buffer.from(String(part)); chunks.push(Buffer.from(`$${value.length}\r\n`), value, Buffer.from("\r\n")); } return Buffer.concat(chunks); }

function redisJson(value, label) { let encoded; try { encoded = JSON.stringify(value); } catch { throw new Error(`invalid Redis ${label} payload`); } if (typeof encoded !== "string") throw new Error(`invalid Redis ${label} payload`); return encoded; }

export function compileRedisHotSync(state, batch, ttlSeconds = 86_400, maxBytes = 16_777_216) {
  if (!Number.isInteger(ttlSeconds) || ttlSeconds < 300 || !Number.isInteger(maxBytes) || maxBytes < 65_536 || !Number.isSafeInteger(batch?.toSequence) || batch.toSequence < 0 || !Array.isArray(batch?.events) || !state?.pools || typeof state.pools !== "object" || Array.isArray(state.pools) || !state?.mints || typeof state.mints !== "object" || Array.isArray(state.mints)) throw new Error("invalid Redis hot-state configuration");
  const version = batch.toSequence, prefix = `terminal_dex:hot:${version}`, poolKey = `${prefix}:pools`, tokenKey = `${prefix}:tokens`, commands = [respCommand(["DEL", poolKey, tokenKey])];
  for (const [address, row] of Object.entries(state.pools).sort(([left], [right]) => left.localeCompare(right))) { if (!address || /[\u0000-\u001f]/.test(address)) throw new Error("invalid Redis pool identity"); commands.push(respCommand(["HSET", poolKey, address, redisJson(row, "pool")])); }
  for (const [mint, row] of Object.entries(state.mints).sort(([left], [right]) => left.localeCompare(right))) { if (!mint || /[\u0000-\u001f]/.test(mint)) throw new Error("invalid Redis mint identity"); commands.push(respCommand(["HSET", tokenKey, mint, redisJson(row, "mint")])); }
  commands.push(respCommand(["MULTI"]), respCommand(["SET", "terminal_dex:hot:current", String(version)]), respCommand(["SET", `${prefix}:stats`, redisJson({ tip: state.tip ?? null, eventSequence: state.eventSequence, pools: Object.keys(state.pools).length, tokens: Object.keys(state.mints).length, updatedAt: state.updatedAt ?? null }, "stats")]), respCommand(["EXPIRE", poolKey, ttlSeconds]), respCommand(["EXPIRE", tokenKey, ttlSeconds]), respCommand(["EXPIRE", `${prefix}:stats`, ttlSeconds]));
  for (const event of batch.events) { if (typeof event?.payload !== "string") throw new Error("invalid Redis event payload"); commands.push(respCommand(["PUBLISH", "terminal_dex:canonical_events", event.payload])); } commands.push(respCommand(["EXEC"])); const payload = Buffer.concat(commands); if (payload.length > maxBytes) throw new Error("Redis hot-state batch exceeds configured byte limit"); return payload;
}

export function compileWarehouseProjections(store, staleAfterMs = 120_000, limit = 500) {
  const blockTimes = Object.values(store?.state?.blocks ?? {}).map((row) => Number(row?.blockTime) * 1_000).filter(Number.isFinite), now = blockTimes.length ? blockTimes.reduce((latest, value) => Math.max(latest, value), 0) : Date.parse(store?.state?.updatedAt ?? ""); if (!Number.isFinite(now) || !Number.isInteger(staleAfterMs) || staleAfterMs < 1_000 || !Number.isInteger(limit) || limit < 1 || limit > 10_000) throw new Error("invalid warehouse projection context");
  const candidates = store.trending(limit, 86_400, now).map((row) => { if (!row.mint || !Number.isSafeInteger(row.swapCount) || row.swapCount < 0 || !Number.isSafeInteger(row.uniqueTraders) || row.uniqueTraders < 0 || !Number.isSafeInteger(row.transferCount) || row.transferCount < 0) throw new Error("invalid warehouse candidate projection"); const score = row.swapCount * 1_000_000 + row.uniqueTraders * 1_000 + row.transferCount; if (!Number.isSafeInteger(score)) throw new Error("warehouse candidate score overflow"); return { mint: row.mint, scoreVersion: "activity-v1", score, state: "review_required", evidence: { schemaVersion: 1, asOf: new Date(now).toISOString(), windowSeconds: 86_400, activity: row, automationSafe: false } }; });
  const security = Object.keys(store.state.mints).sort().map((mint) => store.tokenSecurity(mint, staleAfterMs, now)).filter((row) => row.evidence?.slot != null).map((row) => { if (!row.mint || row.ruleVersion !== "token-security-v1" || !Number.isSafeInteger(row.evidence.slot) || row.evidence.slot < 0 || !Array.isArray(row.findings)) throw new Error("invalid warehouse security projection"); const blocking = !row.assessable || row.findings.some((finding) => finding.blocksAutomation), severity = row.findings.some((finding) => finding.severity === "high") ? "high" : row.findings.some((finding) => finding.severity === "medium") ? "medium" : row.assessable ? "low" : "unknown"; return { mint: row.mint, ruleVersion: row.ruleVersion, sourceSlot: row.evidence.slot, severity, blocksResearch: false, blocksEntry: blocking, blocksExit: false, observedAt: new Date(now).toISOString(), expiresAt: new Date(now + staleAfterMs).toISOString(), evidence: row }; });
  const stale = (observedAt) => { const observed = Date.parse(observedAt ?? ""); return !Number.isFinite(observed) || observed > now || now - observed > staleAfterMs; }, jobs = [], tokenPrograms = new Set(["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"]);
  for (const mint of Object.keys(store.state.mints).sort()) { const snapshot = store.state.holderSnapshots[mint], incomplete = snapshot && !isCanonicalAccountSnapshotEvidence(snapshot, store.state.mints[mint]?.mintInfo); if (!snapshot || incomplete || stale(snapshot.observedAt)) jobs.push({ key: `account-snapshot:${mint}`, type: "account_snapshot", payload: { schemaVersion: 1, chain: CHAIN, mint, reason: !snapshot ? "missing" : incomplete ? "incomplete_account_evidence" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: snapshot?.slot ?? null } }); }
  for (const [mint, row] of Object.entries(store.state.mints).sort(([left], [right]) => left.localeCompare(right))) { const canonical = row.metadata, enriched = row.offchainMetadata, enrichmentAge = now - Date.parse(enriched?.observedAt ?? ""), refresh = !enriched || !Number.isFinite(enrichmentAge) || enrichmentAge < 0 || enrichmentAge > 86_400_000; if (canonical?.uri?.startsWith("https://") && /^[0-9a-f]{64}$/.test(canonical.rawPayloadHash ?? "") && refresh) jobs.push({ key: `offchain-metadata-snapshot:${mint}`, type: "offchain_metadata_snapshot", payload: { schemaVersion: 1, chain: CHAIN, mint, uri: canonical.uri, onchainMetadataHash: canonical.rawPayloadHash, reason: !enriched ? "missing" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: row.authoritySourceSlot ?? row.lastSlot ?? null } }); }
  const completeClmmQuoteEvidence = (snapshot) => snapshot?.commitment === "finalized" && Number.isSafeInteger(snapshot.stateSlot) && Number.isSafeInteger(snapshot.balanceSlot) && snapshot.stateSlot <= snapshot.balanceSlot && snapshot.tickArrayCoverage === "finalized_program_account_snapshot" && Number.isSafeInteger(snapshot.tickArraySlot) && snapshot.tickArraySlot >= snapshot.stateSlot && snapshot.tickArraySlot <= snapshot.balanceSlot && Number.isSafeInteger(snapshot.ammConfigSlot) && snapshot.ammConfigSlot >= snapshot.stateSlot && snapshot.ammConfigSlot <= snapshot.balanceSlot && validateBoundPoolMintEvidence(snapshot, snapshot.balanceSlot) && Array.isArray(snapshot.tickArrays) && snapshot.defaultTickArrayBitmap && /^[0-9a-f]{64}$/.test(snapshot.rawPayloadHash ?? "") && /^[0-9a-f]{64}$/.test(snapshot.ammConfigState?.rawPayloadHash ?? "") && Number.isInteger(snapshot.ammConfigState?.tradeFeeRate) && Number.isInteger(snapshot.status) && snapshot.status >= 0 && snapshot.status <= 255 && [0, 1, 2].includes(snapshot.feeOn) && typeof snapshot.dynamicFeeEnabled === "boolean" && [snapshot.vault0AmountRaw, snapshot.vault1AmountRaw, snapshot.liquidityRaw, snapshot.sqrtPriceX64].every((value) => /^\d+$/.test(value ?? ""));
  for (const [pool, row] of Object.entries(store.state.pools).sort(([left], [right]) => left.localeCompare(right))) if (row.protocol === "raydium-clmm") { const snapshot = row.accountSnapshot, incomplete = snapshot && !completeClmmQuoteEvidence(snapshot); if (!snapshot || incomplete || stale(snapshot.observedAt)) jobs.push({ key: `clmm-pool-snapshot:${pool}`, type: "clmm_pool_snapshot", payload: { schemaVersion: 1, chain: CHAIN, pool, reason: !snapshot ? "missing" : incomplete ? "incomplete_quote_evidence" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: snapshot?.stateSlot ?? null } }); }
  const completeCpmmQuoteEvidence = (snapshot) => snapshot?.commitment === "finalized" && Number.isSafeInteger(snapshot.stateSlot) && Number.isSafeInteger(snapshot.configSlot) && Number.isSafeInteger(snapshot.balanceSlot) && snapshot.stateSlot <= snapshot.configSlot && snapshot.configSlot <= snapshot.balanceSlot && snapshot.ammConfigSlot === snapshot.configSlot && typeof snapshot.tokenProgram0 === "string" && typeof snapshot.tokenProgram1 === "string" && validateBoundPoolMintEvidence(snapshot, snapshot.balanceSlot) && [snapshot.vault0AmountRaw, snapshot.vault1AmountRaw, snapshot.protocolFeesToken0Raw, snapshot.protocolFeesToken1Raw, snapshot.fundFeesToken0Raw, snapshot.fundFeesToken1Raw, snapshot.creatorFeesToken0Raw, snapshot.creatorFeesToken1Raw].every((value) => /^\d+$/.test(value ?? "")) && Number.isInteger(snapshot.status) && snapshot.status >= 0 && snapshot.status <= 255 && [0, 1, 2].includes(snapshot.creatorFeeOn) && typeof snapshot.enableCreatorFee === "boolean" && /^[0-9a-f]{64}$/.test(snapshot.rawPayloadHash ?? "") && /^[0-9a-f]{64}$/.test(snapshot.ammConfigState?.rawPayloadHash ?? "") && [snapshot.ammConfigState?.tradeFeeRate, snapshot.ammConfigState?.creatorFeeRate].every((value) => /^\d+$/.test(value ?? ""));
  for (const [pool, row] of Object.entries(store.state.pools).sort(([left], [right]) => left.localeCompare(right))) if (row.protocol === "raydium-cpmm") { const snapshot = row.accountSnapshot, incomplete = snapshot && !completeCpmmQuoteEvidence(snapshot); if (!snapshot || incomplete || stale(snapshot.observedAt)) jobs.push({ key: `cpmm-pool-snapshot:${pool}`, type: "cpmm_pool_snapshot", payload: { schemaVersion: 1, chain: CHAIN, pool, reason: !snapshot ? "missing" : incomplete ? "incomplete_quote_evidence" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: snapshot?.stateSlot ?? null } }); }
  const completePumpSwapEvidence = (snapshot) => snapshot?.commitment === "finalized" && Number.isSafeInteger(snapshot.stateSlot) && Number.isSafeInteger(snapshot.balanceSlot) && Number.isSafeInteger(snapshot.configSlot) && snapshot.stateSlot <= snapshot.balanceSlot && snapshot.balanceSlot <= snapshot.configSlot && snapshot.feeConfigSlot === snapshot.configSlot && snapshot.globalConfigSlot === snapshot.configSlot && tokenPrograms.has(snapshot.tokenProgram0) && tokenPrograms.has(snapshot.tokenProgram1) && validateBoundPoolMintEvidence(snapshot, snapshot.configSlot) && [snapshot.vault0AmountRaw, snapshot.vault1AmountRaw, snapshot.baseMintSupplyRaw].every((value) => /^\d+$/.test(value ?? "")) && typeof snapshot.canonicalPumpPool === "boolean" && typeof snapshot.cashbackCoin === "boolean" && Number.isInteger(snapshot.globalConfig?.disableFlags) && snapshot.globalConfig.disableFlags >= 0 && snapshot.globalConfig.disableFlags <= 31 && typeof snapshot.globalConfig?.isCashbackEnabled === "boolean" && typeof snapshot.globalConfig?.buybackBasisPoints === "string" && /^\d+$/.test(snapshot.globalConfig.buybackBasisPoints) && BigInt(snapshot.globalConfig.buybackBasisPoints) <= 10_000n && /^[0-9a-f]{64}$/.test(snapshot.feeConfig?.rawPayloadHash ?? "") && /^[0-9a-f]{64}$/.test(snapshot.globalConfig?.rawPayloadHash ?? "");
  for (const [pool, row] of Object.entries(store.state.pools).sort(([left], [right]) => left.localeCompare(right))) if (row.protocol === "pump-swap") { const snapshot = row.accountSnapshot, incomplete = snapshot && !completePumpSwapEvidence(snapshot); if (!snapshot || incomplete || stale(snapshot.observedAt)) jobs.push({ key: `pump-swap-pool-snapshot:${pool}`, type: "pump_swap_pool_snapshot", payload: { schemaVersion: 1, chain: CHAIN, pool, reason: !snapshot ? "missing" : incomplete ? "incomplete_execution_evidence" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: snapshot?.stateSlot ?? null } }); }
  const completePumpExecutionEvidence = (snapshot) => { const expectedQuoteMint = snapshot?.quoteMint === "11111111111111111111111111111111" ? "So11111111111111111111111111111111111111112" : snapshot?.quoteMint, adapter = { ...snapshot, tokenMint0: snapshot?.mint, tokenMint1: expectedQuoteMint, tokenProgram0: snapshot?.baseTokenProgram, tokenProgram1: snapshot?.quoteTokenProgram, mintDecimals0: snapshot?.baseDecimals, mintDecimals1: snapshot?.quoteDecimals }, buyback = snapshot?.global?.buybackBasisPoints; return snapshot?.commitment === "finalized" && Number.isSafeInteger(snapshot.stateSlot) && Number.isSafeInteger(snapshot.mintSlot) && Number.isSafeInteger(snapshot.configSlot) && snapshot.stateSlot <= snapshot.mintSlot && snapshot.mintSlot <= snapshot.configSlot && tokenPrograms.has(snapshot.baseTokenProgram) && tokenPrograms.has(snapshot.quoteTokenProgram) && snapshot.executionQuoteMint === expectedQuoteMint && validateBoundPoolMintEvidence(adapter, snapshot.configSlot) && typeof snapshot.cashbackCoin === "boolean" && typeof buyback === "string" && /^\d+$/.test(buyback) && BigInt(buyback) <= 10_000n && /^[0-9a-f]{64}$/.test(snapshot.feeConfig?.rawPayloadHash ?? "") && typeof snapshot.global?.address === "string" && typeof snapshot.feeConfig?.address === "string"; };
  const scheduledPumpMints = new Set(); for (const row of Object.values(store.state.pools)) if (row.protocol === "pump-bonding-curve" && row.baseMint && !scheduledPumpMints.has(row.baseMint)) { const snapshot = row.accountSnapshot, incomplete = snapshot && !completePumpExecutionEvidence(snapshot); if (!snapshot || incomplete || stale(snapshot.observedAt)) { scheduledPumpMints.add(row.baseMint); jobs.push({ key: `pump-bonding-curve-snapshot:${row.baseMint}`, type: "pump_bonding_curve_snapshot", payload: { schemaVersion: 1, chain: CHAIN, mint: row.baseMint, reason: !snapshot ? "missing" : incomplete ? "incomplete_execution_evidence" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: snapshot?.stateSlot ?? null } }); } }
  const completeOrcaQuoteEvidence = (snapshot) => snapshot?.programId === ORCA_WHIRLPOOL_PROGRAM && typeof snapshot.address === "string" && snapshot.address && snapshot.commitment === "finalized" && Number.isSafeInteger(snapshot.stateSlot) && Number.isSafeInteger(snapshot.tickArraySlot) && Number.isSafeInteger(snapshot.balanceSlot) && snapshot.stateSlot <= snapshot.tickArraySlot && snapshot.tickArraySlot <= snapshot.balanceSlot && snapshot.tickArrayCoverage === "finalized_program_account_snapshot" && Array.isArray(snapshot.tickArrays) && snapshot.tickArrays.length <= 2_048 && new Set(snapshot.tickArrays.map((array) => array?.address)).size === snapshot.tickArrays.length && new Set(snapshot.tickArrays.map((array) => array?.startTickIndex)).size === snapshot.tickArrays.length && tokenPrograms.has(snapshot.tokenProgram0) && tokenPrograms.has(snapshot.tokenProgram1) && validateBoundPoolMintEvidence(snapshot, snapshot.balanceSlot) && Number.isInteger(snapshot.tickSpacing) && snapshot.tickSpacing > 0 && Number.isInteger(snapshot.tick) && snapshot.tick >= -443_636 && snapshot.tick <= 443_636 && Number.isInteger(snapshot.feeRate) && snapshot.feeRate >= 0 && snapshot.feeRate < 1_000_000 && Number.isInteger(snapshot.protocolFeeRate) && snapshot.protocolFeeRate >= 0 && snapshot.protocolFeeRate < 1_000_000 && [snapshot.vault0AmountRaw, snapshot.vault1AmountRaw, snapshot.liquidityRaw, snapshot.sqrtPriceX64].every((value) => /^\d+$/.test(value ?? "")) && /^[0-9a-f]{64}$/.test(snapshot.rawPayloadHash ?? "") && snapshot.tickArrays.every((array) => typeof array?.address === "string" && array.address && array.pool === snapshot.address && ["fixed", "dynamic"].includes(array.type) && Number.isInteger(array.startTickIndex) && Array.isArray(array.initializedTicks) && array.initializedTickCount === array.initializedTicks.length && /^[0-9a-f]{64}$/.test(array.rawPayloadHash ?? ""));
  for (const [pool, row] of Object.entries(store.state.pools).sort(([left], [right]) => left.localeCompare(right))) if (row.protocol === "orca-whirlpool") { const snapshot = row.accountSnapshot, incomplete = snapshot && !completeOrcaQuoteEvidence(snapshot); if (!snapshot || incomplete || stale(snapshot.observedAt)) jobs.push({ key: `orca-pool-snapshot:${pool}`, type: "orca_pool_snapshot", payload: { schemaVersion: 1, chain: CHAIN, pool, reason: !snapshot ? "missing" : incomplete ? "incomplete_quote_evidence" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: snapshot?.stateSlot ?? null } }); }
  return { candidates, security, jobs };
}

export function compileWarehouseMetadataSql(state, sequence, projections = { candidates: [], security: [], jobs: [] }) {
  if (!state?.mints || typeof state.mints !== "object" || Array.isArray(state.mints)) throw new Error("invalid warehouse mint state"); checkpointSql(sequence);
  const rows = Object.entries(state.mints).sort(([left], [right]) => left.localeCompare(right)).map(([mint, row]) => { const info = row?.mintInfo ?? null, decimals = info?.decimals ?? null, sourceSlot = row?.authoritySourceSlot ?? row?.lastSlot ?? null, transferCount = row?.transferCount ?? 0, swapCount = row?.swapCount ?? 0, lastSlot = row?.lastSlot ?? null, lastBlockTime = row?.lastBlockTime ?? null; if (!mint || /[\u0000-\u001f]/.test(mint) || (decimals != null && (!Number.isInteger(decimals) || decimals < 0 || decimals > 255)) || (sourceSlot != null && (!Number.isSafeInteger(sourceSlot) || sourceSlot < 0)) || !Number.isSafeInteger(transferCount) || transferCount < 0 || !Number.isSafeInteger(swapCount) || swapCount < 0 || (lastSlot != null && (!Number.isSafeInteger(lastSlot) || lastSlot < 0)) || (lastBlockTime != null && (!Number.isSafeInteger(lastBlockTime) || lastBlockTime < 0))) throw new Error(`invalid warehouse mint metadata ${mint}`); const metadata = { transferCount, swapCount, lastSlot, lastBlockTime, tokenMetadata: row?.metadata ?? null, offchainTokenMetadata: row?.offchainMetadata ?? null }, authorities = { mintAuthority: info?.mintAuthority ?? null, freezeAuthority: info?.freezeAuthority ?? null }, extensions = Array.isArray(info?.extensions) ? info.extensions : []; return `('solana', ${sqlLiteral(mint)}, ${decimals ?? "NULL"}, ${jsonbLiteral(metadata)}, ${jsonbLiteral(authorities)}, ${jsonbLiteral(extensions)}, ${sourceSlot ?? "NULL"})`; });
  if (!Array.isArray(projections?.candidates) || !Array.isArray(projections?.security) || !Array.isArray(projections?.jobs ?? [])) throw new Error("invalid warehouse projections");
  const candidateRows = projections.candidates.map((row) => { if (!row.mint || !row.scoreVersion || !Number.isSafeInteger(row.score) || !["review_required", "eligible", "rejected"].includes(row.state)) throw new Error("invalid warehouse candidate row"); return `(${sqlLiteral(CHAIN)}, ${sqlLiteral(row.mint)}, ${sqlLiteral(row.scoreVersion)}, ${jsonbLiteral(row.evidence)}, ${row.score}, ${sqlLiteral(row.state)})`; });
  const securityRows = projections.security.map((row) => { if (!row.mint || !row.ruleVersion || !Number.isSafeInteger(row.sourceSlot) || row.sourceSlot < 0 || !["unknown", "low", "medium", "high"].includes(row.severity) || typeof row.blocksResearch !== "boolean" || typeof row.blocksEntry !== "boolean" || typeof row.blocksExit !== "boolean" || !Number.isFinite(Date.parse(row.observedAt)) || !Number.isFinite(Date.parse(row.expiresAt))) throw new Error("invalid warehouse security row"); return `(${sqlLiteral(CHAIN)}, ${sqlLiteral(row.mint)}, ${sqlLiteral(row.ruleVersion)}, ${row.sourceSlot}, NULL, ${jsonbLiteral(row.evidence)}, ${sqlLiteral(row.severity)}, ${row.blocksResearch}, ${row.blocksEntry}, ${row.blocksExit}, ${sqlLiteral(row.observedAt)}, ${sqlLiteral(row.expiresAt)})`; });
  const jobRows = (projections.jobs ?? []).map((row) => { if (!/^[a-z0-9_-]+:[^\u0000-\u001f]+$/.test(row.key ?? "") || !["account_snapshot", "cpmm_pool_snapshot", "pump_swap_pool_snapshot", "pump_bonding_curve_snapshot", "clmm_pool_snapshot", "orca_pool_snapshot", "offchain_metadata_snapshot"].includes(row.type) || row.payload?.schemaVersion !== 1 || row.payload?.chain !== CHAIN) throw new Error("invalid warehouse operational job"); return `(${sqlLiteral(row.key)}, ${sqlLiteral(row.type)}, ${jsonbLiteral(row.payload)}, 'pending', 0, now())`; });
  const activeJobKeys = `ARRAY[${(projections.jobs ?? []).map((row) => sqlLiteral(row.key)).join(", ")}]::text[]`;
  return `BEGIN;\n${rows.length ? `INSERT INTO tokens (chain, mint, decimals, metadata, authorities, extensions, source_slot) VALUES\n${rows.join(",\n")}\nON CONFLICT (chain, mint) DO UPDATE SET decimals = EXCLUDED.decimals, metadata = EXCLUDED.metadata, authorities = EXCLUDED.authorities, extensions = EXCLUDED.extensions, source_slot = EXCLUDED.source_slot, updated_at = now();\n` : ""}${candidateRows.length ? `INSERT INTO candidates (chain, mint, score_version, evidence_snapshot, score, state) VALUES\n${candidateRows.join(",\n")}\nON CONFLICT (chain, mint, score_version) DO UPDATE SET evidence_snapshot = EXCLUDED.evidence_snapshot, score = EXCLUDED.score, state = EXCLUDED.state, updated_at = now();\n` : ""}${securityRows.length ? `INSERT INTO security_snapshots (chain, mint, rule_version, source_slot, source_signature, evidence, severity, blocks_research, blocks_entry, blocks_exit, observed_at, expires_at) VALUES\n${securityRows.join(",\n")}\nON CONFLICT (chain, mint, rule_version, source_slot) WHERE source_slot IS NOT NULL DO UPDATE SET evidence = EXCLUDED.evidence, severity = EXCLUDED.severity, blocks_research = EXCLUDED.blocks_research, blocks_entry = EXCLUDED.blocks_entry, blocks_exit = EXCLUDED.blocks_exit, observed_at = EXCLUDED.observed_at, expires_at = EXCLUDED.expires_at;\n` : ""}UPDATE operational_jobs SET status = 'cancelled', updated_at = now() WHERE job_type IN ('account_snapshot', 'cpmm_pool_snapshot', 'pump_swap_pool_snapshot', 'pump_bonding_curve_snapshot', 'clmm_pool_snapshot', 'orca_pool_snapshot', 'offchain_metadata_snapshot') AND status = 'pending' AND NOT (job_key = ANY(${activeJobKeys}));\n${jobRows.length ? `INSERT INTO operational_jobs (job_key, job_type, payload, status, attempts, available_at) VALUES\n${jobRows.join(",\n")}\nON CONFLICT (job_key) WHERE job_key IS NOT NULL DO UPDATE SET job_type = CASE WHEN operational_jobs.status = 'running' THEN operational_jobs.job_type ELSE EXCLUDED.job_type END, payload = CASE WHEN operational_jobs.status = 'running' THEN operational_jobs.payload ELSE EXCLUDED.payload END, status = CASE WHEN operational_jobs.status = 'running' THEN operational_jobs.status ELSE 'pending' END, attempts = CASE WHEN operational_jobs.status = 'running' THEN operational_jobs.attempts ELSE 0 END, available_at = CASE WHEN operational_jobs.status = 'running' THEN operational_jobs.available_at ELSE now() END, updated_at = now();\n` : ""}${checkpointSql(sequence)}COMMIT;\n`;
}

export function assessWarehouseCheckpoint(checkpoint, eventSequence, oldestSequence, staleAfterMs = 300_000, maxLagEvents = 1_000, now = Date.now()) {
  const unavailable = (reason) => ({ available: false, healthy: false, reason, sequence: null, eventSequence, lagEvents: null, ageMs: null, staleAfterMs, maxLagEvents });
  if (!checkpoint) return unavailable("checkpoint_unavailable");
  const updated = Date.parse(checkpoint.updatedAt ?? ""), sequence = Number(checkpoint.lastSequence);
  if (checkpoint.schemaVersion !== 1 || checkpoint.consumer !== "warehouse-canonical-events" || !Number.isSafeInteger(sequence) || sequence < 0 || !Number.isSafeInteger(eventSequence) || eventSequence < 0 || !Number.isSafeInteger(oldestSequence) || oldestSequence < 1 || !Number.isFinite(updated)) return unavailable("checkpoint_invalid");
  const sinks = checkpoint.sinks;
  if (!sinks || ![sinks.clickhouse, sinks.postgres, sinks.redis].every((value) => Number.isSafeInteger(value) && value >= 0)) return { ...unavailable("sink_evidence_unavailable"), sequence };
  if ([sinks.clickhouse, sinks.postgres, sinks.redis].some((value) => value !== sequence)) return { ...unavailable("sink_sequence_mismatch"), sequence, sinks };
  const reconciliation = checkpoint.reconciliation; if (!reconciliation || reconciliation.schemaVersion !== 1 || reconciliation.verified !== true || reconciliation.sequence !== sequence || ["events", "instructions", "swaps", "balanceChanges", "nativeTransfers", "deadLetters", "tokens", "pools"].some((key) => !Number.isSafeInteger(reconciliation[key]) || reconciliation[key] < 0)) return { ...unavailable("content_reconciliation_unavailable"), sequence, sinks };
  if (sequence > eventSequence) return { ...unavailable("checkpoint_ahead_of_index"), sequence };
  const lagEvents = eventSequence - sequence, ageMs = now - updated, replayHistoryLost = sequence < oldestSequence - 1, reason = ageMs < 0 ? "checkpoint_clock_skew" : replayHistoryLost ? "checkpoint_behind_replay_history" : lagEvents > maxLagEvents ? "warehouse_lag_exceeded" : ageMs > staleAfterMs ? "warehouse_checkpoint_stale" : null;
  return { available: true, healthy: reason == null, reason, sequence, eventSequence, oldestSequence, lagEvents, ageMs, staleAfterMs, maxLagEvents, replayHistoryLost, sinks, reconciliation };
}

function runProcess(command, args, input, spawnProcess = spawn, env = process.env) {
  return new Promise((resolve, reject) => { const child = spawnProcess(command, args, { shell: false, windowsHide: true, stdio: ["pipe", "ignore", "pipe"], env }); let errorText = ""; child.stderr.on("data", (chunk) => { if (errorText.length < 8_192) errorText += chunk; }); child.on("error", reject); child.on("close", (code) => code === 0 ? resolve() : reject(new Error(`${command} warehouse sync failed (${code}): ${errorText.trim().slice(0, 512)}`))); child.stdin.end(input); });
}

function captureProcess(command, args, spawnProcess = spawn, env = process.env) {
  return new Promise((resolve, reject) => { const child = spawnProcess(command, args, { shell: false, windowsHide: true, stdio: ["ignore", "pipe", "pipe"], env }); let output = "", errorText = ""; child.stdout.on("data", (chunk) => { if (output.length < 1_024) output += chunk; }); child.stderr.on("data", (chunk) => { if (errorText.length < 8_192) errorText += chunk; }); child.on("error", reject); child.on("close", (code) => code === 0 ? resolve(output.trim()) : reject(new Error(`${command} warehouse probe failed (${code}): ${errorText.trim().slice(0, 512)}`))); });
}

export function validateWarehouseSinkSequences(expectedSequence, values) {
  if (!Number.isSafeInteger(expectedSequence) || expectedSequence < 0) throw new Error("invalid expected warehouse sequence");
  const sinks = {};
  for (const name of ["clickhouse", "postgres", "redis"]) { const text = String(values?.[name] ?? "").trim(); if (!/^\d+$/.test(text)) throw new Error(`${name} warehouse sequence unavailable`); const sequence = Number(text); if (!Number.isSafeInteger(sequence) || sequence !== expectedSequence) throw new Error(`${name} warehouse sequence mismatch`); sinks[name] = sequence; }
  return sinks;
}

export function expectedWarehouseReconciliation(state, sequence) {
  if (!Number.isSafeInteger(sequence) || sequence < 0 || !state || !Array.isArray(state.instructions) || !Array.isArray(state.swaps) || !Array.isArray(state.balanceChanges) || !Array.isArray(state.nativeTransfers) || !Array.isArray(state.deadLetters) || !state.mints || typeof state.mints !== "object" || Array.isArray(state.mints) || !state.pools || typeof state.pools !== "object" || Array.isArray(state.pools)) throw new Error("invalid warehouse reconciliation state");
  return { sequence, events: sequence, instructions: state.instructions.length, swaps: state.swaps.length, balanceChanges: state.balanceChanges.length, nativeTransfers: state.nativeTransfers.length, deadLetters: state.deadLetters.length, tokens: Object.keys(state.mints).length, pools: Object.keys(state.pools).length };
}

function numericLines(value, count, label) { const lines = String(value ?? "").trim().split(/\r?\n/), numbers = lines.map(Number); if (lines.length !== count || lines.some((line) => !/^\d+$/.test(line)) || numbers.some((number) => !Number.isSafeInteger(number))) throw new Error(`${label} reconciliation evidence unavailable`); return numbers; }
export function validateWarehouseReconciliation(expected, values) {
  const keys = ["sequence", "events", "instructions", "swaps", "balanceChanges", "nativeTransfers", "deadLetters", "tokens", "pools"]; if (!expected || keys.some((key) => !Number.isSafeInteger(expected[key]) || expected[key] < 0)) throw new Error("invalid expected warehouse reconciliation");
  const clickhouse = numericLines(values?.clickhouse, 6, "clickhouse"), postgres = numericLines(values?.postgres, 2, "postgres"), redis = numericLines(values?.redis, 3, "redis"), actual = { sequence: postgres[0], events: clickhouse[0], instructions: clickhouse[1], swaps: clickhouse[2], balanceChanges: clickhouse[3], nativeTransfers: clickhouse[4], deadLetters: clickhouse[5], tokens: postgres[1], pools: redis[1] };
  if (redis[0] !== expected.sequence || redis[2] !== expected.tokens || keys.some((key) => actual[key] !== expected[key])) throw new Error("warehouse content reconciliation mismatch"); return { schemaVersion: 1, verified: true, ...expected };
}

export async function probeWarehouseReconciliation(expected, spawnProcess = spawn, env = process.env) {
  const [clickhouse, postgres, redis] = await Promise.all([
    captureProcess("clickhouse-client", ["--query", "SELECT uniqExact(sequence) FROM terminal_dex.canonical_events UNION ALL SELECT uniqExact(event_id) FROM terminal_dex.canonical_instructions UNION ALL SELECT uniqExact(swap_id) FROM terminal_dex.canonical_swaps UNION ALL SELECT uniqExact(tuple(signature, account_index)) FROM terminal_dex.canonical_balance_changes UNION ALL SELECT uniqExact(transfer_id) FROM terminal_dex.canonical_native_transfers UNION ALL SELECT uniqExact(identity) FROM terminal_dex.canonical_dead_letters FORMAT TabSeparatedRaw"], spawnProcess, env),
    captureProcess("psql", ["--no-psqlrc", "--set", "ON_ERROR_STOP=1", "--tuples-only", "--no-align", "--quiet", "--command", "SELECT COALESCE(cursor, '0') FROM ingestion_checkpoints WHERE consumer='warehouse-canonical-events'; SELECT count(*) FROM tokens WHERE chain='solana-mainnet';"], spawnProcess, env),
    captureProcess("redis-cli", ["--raw", "EVAL", "return {redis.call('GET','terminal_dex:hot:current') or '0',redis.call('HLEN','terminal_dex:hot:'..ARGV[1]..':pools'),redis.call('HLEN','terminal_dex:hot:'..ARGV[1]..':tokens')}", "0", String(expected.sequence)], spawnProcess, env),
  ]);
  return validateWarehouseReconciliation(expected, { clickhouse, postgres, redis });
}

export async function probeWarehouseSinks(expectedSequence, spawnProcess = spawn, env = process.env) {
  const [clickhouse, postgres, redis] = await Promise.all([
    captureProcess("clickhouse-client", ["--query", "SELECT toString(ifNull(max(sequence), 0)) FROM terminal_dex.canonical_events FORMAT TabSeparatedRaw"], spawnProcess, env),
    captureProcess("psql", ["--no-psqlrc", "--set", "ON_ERROR_STOP=1", "--tuples-only", "--no-align", "--quiet", "--command", "SELECT COALESCE(cursor, '') FROM ingestion_checkpoints WHERE consumer='warehouse-canonical-events'"], spawnProcess, env),
    captureProcess("redis-cli", ["--raw", "GET", "terminal_dex:hot:current"], spawnProcess, env),
  ]);
  return validateWarehouseSinkSequences(expectedSequence, { clickhouse, postgres, redis });
}

export async function syncWarehouseBatch(batch, spawnProcess = spawn, env = process.env, facts = null, postgresSql = checkpointSql(batch.toSequence), redisInput = null) {
  if (!batch.events.length) return { synced: 0, sequence: batch.toSequence };
  if (facts && (!Array.isArray(facts.slots) || facts.slots.some((slot) => !Number.isSafeInteger(slot) || slot < 0) || !Array.isArray(facts.instructions) || !Array.isArray(facts.swaps) || !Array.isArray(facts.balanceChanges) || !Array.isArray(facts.nativeTransfers) || !Array.isArray(facts.deadLetters))) throw new Error("invalid warehouse facts");
  if (typeof postgresSql !== "string" || !postgresSql.trim()) throw new Error("invalid warehouse PostgreSQL transaction");
  if (redisInput != null && !Buffer.isBuffer(redisInput)) throw new Error("invalid Redis hot-state transaction");
  const body = `${batch.events.map((row) => JSON.stringify(row)).join("\n")}\n`;
  await runProcess("clickhouse-client", ["--query", "INSERT INTO terminal_dex.canonical_events FORMAT JSONEachRow"], body, spawnProcess, env);
  if (facts) {
    const suffixes = [["canonical_instructions", facts.instructions], ["canonical_swaps", facts.swaps], ["canonical_balance_changes", facts.balanceChanges], ["canonical_native_transfers", facts.nativeTransfers]];
    if (facts.slots.length) for (const [table, rows] of suffixes) { const slotList = facts.slots.join(","); await runProcess("clickhouse-client", ["--multiquery", "--query", `ALTER TABLE terminal_dex.${table} DELETE WHERE slot IN (${slotList}) SETTINGS mutations_sync = 2`], "", spawnProcess, env); if (rows.length) await runProcess("clickhouse-client", ["--query", `INSERT INTO terminal_dex.${table} FORMAT JSONEachRow`], `${rows.map((row) => JSON.stringify(row)).join("\n")}\n`, spawnProcess, env); }
    await runProcess("clickhouse-client", ["--multiquery", "--query", `ALTER TABLE terminal_dex.canonical_dead_letters DELETE WHERE chain = '${CHAIN}' SETTINGS mutations_sync = 2`], "", spawnProcess, env); if (facts.deadLetters.length) await runProcess("clickhouse-client", ["--query", "INSERT INTO terminal_dex.canonical_dead_letters FORMAT JSONEachRow"], `${facts.deadLetters.map((row) => JSON.stringify(row)).join("\n")}\n`, spawnProcess, env);
    if (facts.candleKeys?.length) { const predicates = facts.candleKeys.map((row) => `(pool=${sqlLiteral(row.pool)} AND interval_seconds=${row.interval} AND bucket_start=${sqlLiteral(new Date(row.bucket * 1_000).toISOString())})`).join(" OR "); await runProcess("clickhouse-client", ["--multiquery", "--query", `ALTER TABLE terminal_dex.canonical_candles DELETE WHERE chain = '${CHAIN}' AND (${predicates}) SETTINGS mutations_sync = 2`], "", spawnProcess, env); if (facts.candles.length) await runProcess("clickhouse-client", ["--query", "INSERT INTO terminal_dex.canonical_candles FORMAT JSONEachRow"], `${facts.candles.map((row) => JSON.stringify(row)).join("\n")}\n`, spawnProcess, env); }
  }
  await runProcess("psql", ["--no-psqlrc", "--set", "ON_ERROR_STOP=1"], postgresSql, spawnProcess, env);
  if (redisInput) await runProcess("redis-cli", ["--pipe"], redisInput, spawnProcess, env);
  return { synced: batch.events.length, sequence: batch.toSequence };
}

export async function writeWarehouseCheckpoint(filename, sequence, sinks, reconciliation) {
  validateWarehouseSinkSequences(sequence, sinks); if (!reconciliation?.verified || reconciliation.sequence !== sequence) throw new Error("verified warehouse reconciliation is required"); const temporary = `${filename}.${process.pid}.tmp`; await fs.mkdir(path.dirname(filename), { recursive: true }); await fs.writeFile(temporary, `${JSON.stringify({ schemaVersion: 1, consumer: "warehouse-canonical-events", lastSequence: sequence, sinks, reconciliation, updatedAt: new Date().toISOString() })}\n`, { mode: 0o600 }); await fs.rename(temporary, filename);
}

async function main() {
  const config = loadConfig(), checkpointFile = config.warehouseCheckpointFile; let checkpoint = { lastSequence: 0 };
  try { checkpoint = JSON.parse(await fs.readFile(checkpointFile, "utf8")); } catch (error) { if (error.code !== "ENOENT") throw error; }
  const clientEnv = { ...process.env }; if (config.clickhousePasswordFile) { const password = (await fs.readFile(config.clickhousePasswordFile, "utf8")).trim(); if (!password) throw new Error("CLICKHOUSE_PASSWORD_FILE is empty"); clientEnv.CLICKHOUSE_PASSWORD = password; } if (config.redisPasswordFile) { const password = (await fs.readFile(config.redisPasswordFile, "utf8")).trim(); if (!password) throw new Error("REDIS_PASSWORD_FILE is empty"); clientEnv.REDISCLI_AUTH = password; }
  const holderExclusions = await loadHolderExclusions(config.holderExclusionsFile), store = new IndexStore(config.dataFile, config.maxTransactions, config.retentionSeconds, holderExclusions); await store.load(); const state = store.state, batch = compileWarehouseBatch(state, checkpoint), facts = compileWarehouseFacts(state, batch), projections = compileWarehouseProjections(store, config.staleAfterMs), postgresSql = compileWarehouseMetadataSql(state, batch.toSequence, projections), redisInput = compileRedisHotSync(state, batch, config.redisHotTtlSeconds, config.redisHotMaxBytes), result = await syncWarehouseBatch(batch, spawn, clientEnv, facts, postgresSql, redisInput), sinks = await probeWarehouseSinks(result.sequence, spawn, clientEnv), reconciliation = await probeWarehouseReconciliation(expectedWarehouseReconciliation(state, result.sequence), spawn, clientEnv); await writeWarehouseCheckpoint(checkpointFile, result.sequence, sinks, reconciliation); console.log(JSON.stringify({ ...result, sinks, reconciliation, candidates: projections.candidates.length, securitySnapshots: projections.security.length, operationalJobs: projections.jobs.length, redisBytes: redisInput.length }));
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main().catch((error) => { console.error(error.message); process.exitCode = 1; });
