import path from "node:path";
import crypto from "node:crypto";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import { loadConfig } from "./config.js";
import { canonicalAggregateProjections, canonicalMetadataProjections, canonicalPersistedDerivedLedger, canonicalPersistedEvent, canonicalPersistedEventLog, canonicalPersistedInstructionLog, canonicalPersistedProgramEventLog, canonicalPersistedSwapLog, canonicalSnapshotProjections, IndexStore, isCanonicalAccountSnapshotEvidence, metadataEvidenceProjection, validClmmBitmap, validClmmBitmapExtension, validMeteoraBitmapExtension } from "./store.js";
import { isCanonicalTokenMetadata } from "./token-metadata.js";
import { isCanonicalOffchainTokenMetadata } from "./offchain-token-metadata.js";
import { loadHolderExclusions } from "./holder-exclusions.js";
import { POOL_MINT_EVIDENCE_CONSTANTS, validateBoundPoolMintEvidence } from "./pool-mint-evidence.js";
import { ORCA_WHIRLPOOL_PROGRAM } from "./orca-pool-snapshot.js";
import { METEORA_DLMM_PROGRAM } from "./meteora-dlmm-pool-snapshot.js";
import { RAYDIUM_CPMM_PROGRAM } from "./cpmm-pool-snapshot.js";
import { RAYDIUM_AMM_V4_PROGRAM } from "./amm-v4-pool-snapshot.js";
import { RAYDIUM_CLMM_PROGRAM } from "./clmm-pool-snapshot.js";
import { derivePumpBondingCurve, derivePumpFeeConfig, derivePumpGlobal, derivePumpSwapFeeConfig, derivePumpSwapGlobalConfig, PUMP_PROGRAM, PUMP_SWAP_PROGRAM } from "./pump-swap-pool-snapshot.js";
import { durableAtomicWrite } from "./durable-file.js";
import { canonicalUnixSecondsToMilliseconds, parseCanonicalUtcTimestamp } from "./canonical-time.js";
import { readSecretFile } from "./secret-file.js";
import { runBoundedProcess } from "./bounded-process.js";
import { readBoundedJsonFile } from "./bounded-json-file.js";

const CHAIN = "solana-mainnet";
const GENESIS_HASH = "5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d";
const PUMP_SWAP_FEE_CONFIG = derivePumpSwapFeeConfig().address;
const PUMP_SWAP_GLOBAL_CONFIG = derivePumpSwapGlobalConfig().address;
const PUMP_FEE_CONFIG = derivePumpFeeConfig(PUMP_PROGRAM).address;
const PUMP_GLOBAL = derivePumpGlobal().address;
export const CANDLE_INTERVALS = [60, 300, 900, 3_600, 14_400, 86_400];

function sqlLiteral(value) { return `'${String(value).replaceAll("'", "''")}'`; }

function completeClmmTickCoverage(snapshot) {
  const defaults = snapshot?.defaultTickArrayBitmap?.initializedTickArrayStartIndexes, extension = snapshot?.bitmapExtension?.initializedTickArrayStartIndexes ?? [], arrays = snapshot?.tickArrays;
  if (!validClmmBitmap(snapshot?.defaultTickArrayBitmap, snapshot?.tickSpacing) || (snapshot?.bitmapExtension ? !validClmmBitmapExtension(snapshot.bitmapExtension, snapshot.address, snapshot.tickSpacing) || !Number.isSafeInteger(snapshot.bitmapExtensionSlot) || snapshot.bitmapExtensionSlot < snapshot.stateSlot || snapshot.bitmapExtensionSlot > snapshot.balanceSlot : snapshot?.bitmapExtensionSlot != null) || !Array.isArray(extension) || !Array.isArray(arrays) || arrays.length > 2_048 || [...defaults, ...extension].some((value) => !Number.isInteger(value))) return false;
  const expected = new Set([...defaults, ...extension]), addresses = new Set(), starts = new Set(); if (expected.size !== defaults.length + extension.length || expected.size !== arrays.length) return false;
  const u128 = (value) => typeof value === "string" && /^\d+$/.test(value) && BigInt(value) <= 340_282_366_920_938_463_463_374_607_431_768_211_455n, i128 = (value) => typeof value === "string" && /^-?\d+$/.test(value) && BigInt(value) >= -170_141_183_460_469_231_731_687_303_715_884_105_728n && BigInt(value) <= 170_141_183_460_469_231_731_687_303_715_884_105_727n;
  for (const array of arrays) { if (typeof array?.address !== "string" || !array.address || addresses.has(array.address) || array.pool !== snapshot.address || !Number.isInteger(array.startTickIndex) || starts.has(array.startTickIndex) || !expected.has(array.startTickIndex) || !Number.isInteger(array.initializedTickCount) || array.initializedTickCount < 0 || array.initializedTickCount > 60 || !Array.isArray(array.initializedTicks) || array.initializedTicks.length !== array.initializedTickCount || typeof array.recentEpoch !== "string" || !/^\d+$/.test(array.recentEpoch) || !/^[0-9a-f]{64}$/.test(array.rawPayloadHash ?? "")) return false; const ticks = new Set(); for (const tick of array.initializedTicks) { const offset = (tick?.tick - array.startTickIndex) / snapshot.tickSpacing; if (!Number.isInteger(tick?.tick) || !Number.isInteger(offset) || offset < 0 || offset >= 60 || ticks.has(tick.tick) || !i128(tick.liquidityNetRaw) || !u128(tick.liquidityGrossRaw) || BigInt(tick.liquidityGrossRaw) === 0n || !u128(tick.feeGrowthOutside0X64) || !u128(tick.feeGrowthOutside1X64) || !Array.isArray(tick.rewardGrowthsOutsideX64) || tick.rewardGrowthsOutsideX64.length !== 3 || !tick.rewardGrowthsOutsideX64.every(u128)) return false; ticks.add(tick.tick); } addresses.add(array.address); starts.add(array.startTickIndex); }
  return true;
}

function completeClmmEconomics(snapshot) {
  const u64 = (value) => typeof value === "string" && /^\d+$/.test(value) && BigInt(value) <= 18_446_744_073_709_551_615n, u128 = (value) => typeof value === "string" && /^\d+$/.test(value) && BigInt(value) <= 340_282_366_920_938_463_463_374_607_431_768_211_455n;
  return typeof snapshot?.tokenMint0 === "string" && snapshot.tokenMint0 && typeof snapshot.tokenMint1 === "string" && snapshot.tokenMint1 && snapshot.tokenMint0 !== snapshot.tokenMint1 && typeof snapshot.tokenVault0 === "string" && snapshot.tokenVault0 && typeof snapshot.tokenVault1 === "string" && snapshot.tokenVault1 && snapshot.tokenVault0 !== snapshot.tokenVault1 && u64(snapshot.vault0AmountRaw) && u64(snapshot.vault1AmountRaw) && u128(snapshot.liquidityRaw) && u128(snapshot.sqrtPriceX64) && /^[0-9a-f]{160}$/.test(snapshot.dynamicFeeRawHex ?? "");
}

function completeCpmmEconomics(snapshot) {
  const config = snapshot?.ammConfigState, values = [snapshot?.vault0AmountRaw, snapshot?.vault1AmountRaw, snapshot?.protocolFeesToken0Raw, snapshot?.protocolFeesToken1Raw, snapshot?.fundFeesToken0Raw, snapshot?.fundFeesToken1Raw, snapshot?.creatorFeesToken0Raw, snapshot?.creatorFeesToken1Raw, snapshot?.openTime, config?.tradeFeeRate, config?.protocolFeeRate, config?.fundFeeRate, config?.creatorFeeRate];
  if (typeof snapshot?.tokenMint0 !== "string" || !snapshot.tokenMint0 || typeof snapshot.tokenMint1 !== "string" || !snapshot.tokenMint1 || snapshot.tokenMint0 === snapshot.tokenMint1 || typeof snapshot.tokenVault0 !== "string" || !snapshot.tokenVault0 || typeof snapshot.tokenVault1 !== "string" || !snapshot.tokenVault1 || snapshot.tokenVault0 === snapshot.tokenVault1 || !values.every((value) => typeof value === "string" && /^\d+$/.test(value) && BigInt(value) <= 18_446_744_073_709_551_615n)) return false;
  const trade = BigInt(config.tradeFeeRate), protocol = BigInt(config.protocolFeeRate), fund = BigInt(config.fundFeeRate), creator = BigInt(config.creatorFeeRate), accrued0 = BigInt(snapshot.protocolFeesToken0Raw) + BigInt(snapshot.fundFeesToken0Raw) + BigInt(snapshot.creatorFeesToken0Raw), accrued1 = BigInt(snapshot.protocolFeesToken1Raw) + BigInt(snapshot.fundFeesToken1Raw) + BigInt(snapshot.creatorFeesToken1Raw);
  return trade + creator < 1_000_000n && protocol + fund <= 1_000_000n && accrued0 <= BigInt(snapshot.vault0AmountRaw) && accrued1 <= BigInt(snapshot.vault1AmountRaw);
}

function completeAmmV4Evidence(snapshot) {
  const u64 = (value) => typeof value === "string" && /^\d+$/.test(value) && BigInt(value) <= 18_446_744_073_709_551_615n, fraction = (value) => u64(value?.numeratorRaw) && u64(value?.denominatorRaw) && BigInt(value.denominatorRaw) > 0n && BigInt(value.numeratorRaw) < BigInt(value.denominatorRaw);
  const orders = snapshot?.openOrdersState, total0 = u64(snapshot?.vault0AmountRaw) && u64(orders?.baseTokenTotalRaw) ? BigInt(snapshot.vault0AmountRaw) + BigInt(orders.baseTokenTotalRaw) : -1n, total1 = u64(snapshot?.vault1AmountRaw) && u64(orders?.quoteTokenTotalRaw) ? BigInt(snapshot.vault1AmountRaw) + BigInt(orders.quoteTokenTotalRaw) : -1n;
  const market = snapshot?.marketState;
  if (!Number.isSafeInteger(snapshot?.marketSlot) || snapshot.marketSlot < snapshot.openOrdersSlot || snapshot.marketSlot > snapshot.balanceSlot || market?.address !== snapshot.market || market?.accountFlagsRaw !== "3" || market?.tokenMint0 !== snapshot.tokenMint0 || market?.tokenMint1 !== snapshot.tokenMint1 || ![market?.vaultSigner, market?.tokenVault0, market?.tokenVault1, market?.requestQueue, market?.eventQueue, market?.bids, market?.asks].every((value) => typeof value === "string" && value) || market.tokenVault0 === market.tokenVault1 || ![market?.vaultSignerNonceRaw, market?.coinLotSizeRaw, market?.pcLotSizeRaw, market?.feeRateBasisPointsRaw].every(u64) || market.coinLotSizeRaw === "0" || market.pcLotSizeRaw === "0" || BigInt(market.feeRateBasisPointsRaw) > 10_000n || !/^[0-9a-f]{64}$/.test(market?.rawPayloadHash ?? "")) return false;
  return completePersistedPoolEnvelope(snapshot) && snapshot?.programId === RAYDIUM_AMM_V4_PROGRAM && snapshot.commitment === "finalized" && Number.isSafeInteger(snapshot.stateSlot) && Number.isSafeInteger(snapshot.openOrdersSlot) && Number.isSafeInteger(snapshot.balanceSlot) && snapshot.stateSlot <= snapshot.openOrdersSlot && snapshot.openOrdersSlot <= snapshot.balanceSlot && Number.isInteger(snapshot.status) && snapshot.status >= 1 && snapshot.status <= 7 && Number.isInteger(snapshot.nonce) && snapshot.nonce >= 0 && snapshot.nonce <= 255 && Number.isInteger(snapshot.state) && snapshot.state >= 0 && snapshot.state <= 6 && [0, 1].includes(snapshot.resetFlag) && Number.isInteger(snapshot.mintDecimals0) && snapshot.mintDecimals0 >= 0 && snapshot.mintDecimals0 <= 255 && Number.isInteger(snapshot.mintDecimals1) && snapshot.mintDecimals1 >= 0 && snapshot.mintDecimals1 <= 255 && typeof snapshot.tokenMint0 === "string" && snapshot.tokenMint0 && typeof snapshot.tokenMint1 === "string" && snapshot.tokenMint1 && snapshot.tokenMint0 !== snapshot.tokenMint1 && typeof snapshot.tokenVault0 === "string" && snapshot.tokenVault0 && typeof snapshot.tokenVault1 === "string" && snapshot.tokenVault1 && snapshot.tokenVault0 !== snapshot.tokenVault1 && [snapshot.lpMint, snapshot.openOrders, snapshot.market, snapshot.marketProgram, snapshot.targetOrders, snapshot.ammOwner, snapshot.poolAuthority].every((value) => typeof value === "string" && value) && orders?.address === snapshot.openOrders && orders?.market === snapshot.market && orders?.owner === snapshot.poolAuthority && orders?.accountFlagsRaw === "5" && [orders?.baseTokenFreeRaw, orders?.baseTokenTotalRaw, orders?.quoteTokenFreeRaw, orders?.quoteTokenTotalRaw].every(u64) && BigInt(orders.baseTokenFreeRaw) <= BigInt(orders.baseTokenTotalRaw) && BigInt(orders.quoteTokenFreeRaw) <= BigInt(orders.quoteTokenTotalRaw) && /^[0-9a-f]{64}$/.test(orders?.rawPayloadHash ?? "") && [snapshot.vault0AmountRaw, snapshot.vault1AmountRaw, snapshot.lpAmountRaw, snapshot.openTime, snapshot.needTakePnl0Raw, snapshot.needTakePnl1Raw, snapshot.reserve0Raw, snapshot.reserve1Raw].every(u64) && BigInt(snapshot.needTakePnl0Raw) <= total0 && BigInt(snapshot.needTakePnl1Raw) <= total1 && BigInt(snapshot.reserve0Raw) === total0 - BigInt(snapshot.needTakePnl0Raw) && BigInt(snapshot.reserve1Raw) === total1 - BigInt(snapshot.needTakePnl1Raw) && [snapshot.minimumSeparation, snapshot.tradeFee, snapshot.pnl, snapshot.swapFee].every(fraction) && /^[0-9a-f]{64}$/.test(snapshot.rawPayloadHash ?? "");
}

function completePumpFeeConfig(config, requireTiers, requireStableTiers = false) {
  const u64 = (value) => typeof value === "string" && /^\d+$/.test(value) && BigInt(value) <= 18_446_744_073_709_551_615n, fees = (value) => [value?.lpFeeBps, value?.protocolFeeBps, value?.creatorFeeBps].every(u64) && BigInt(value.lpFeeBps) + BigInt(value.protocolFeeBps) + BigInt(value.creatorFeeBps) < 10_000n, tiers = (rows, required = false) => Array.isArray(rows) && rows.length <= 256 && (!required || rows.length > 0) && rows.every((row, index) => u64(row?.marketCapLamportsThresholdRaw) && fees(row?.fees) && (!index || BigInt(row.marketCapLamportsThresholdRaw) > BigInt(rows[index - 1].marketCapLamportsThresholdRaw)));
  return typeof config?.admin === "string" && config.admin && Number.isInteger(config.bump) && config.bump >= 0 && config.bump <= 255 && fees(config.flatFees) && tiers(config.feeTiers, requireTiers) && tiers(config.stableFeeTiers, requireStableTiers);
}

function completePumpGlobal(global) {
  const u64 = (value) => typeof value === "string" && /^\d+$/.test(value) && BigInt(value) <= 18_446_744_073_709_551_615n, keys = (value, length) => Array.isArray(value) && value.length === length && value.every((key) => typeof key === "string" && key);
  return global?.initialized === true && typeof global.authority === "string" && global.authority && typeof global.feeRecipient === "string" && global.feeRecipient && [global.initialVirtualTokenReservesRaw, global.initialVirtualQuoteReservesRawLegacy, global.initialRealTokenReservesRaw, global.tokenTotalSupplyRaw, global.feeBasisPoints, global.poolMigrationFeeRaw, global.creatorFeeBasisPoints, global.buybackBasisPoints, global.initialVirtualQuoteReservesRaw].every(u64) && [global.feeBasisPoints, global.creatorFeeBasisPoints, global.buybackBasisPoints].every((value) => BigInt(value) <= 10_000n) && keys(global.feeRecipients, 7) && keys(global.reservedFeeRecipients, 7) && keys(global.buybackFeeRecipients, 8) && keys(global.whitelistedQuoteMints, 1) && [global.enableMigrate, global.createV2Enabled, global.mayhemModeEnabled, global.isCashbackEnabled].every((value) => typeof value === "boolean");
}

function completePumpSwapState(snapshot) {
  const u64 = (value) => typeof value === "string" && /^\d+$/.test(value) && BigInt(value) <= 18_446_744_073_709_551_615n, i128 = (value) => typeof value === "string" && /^-?\d+$/.test(value) && BigInt(value) >= -170_141_183_460_469_231_731_687_303_715_884_105_728n && BigInt(value) <= 170_141_183_460_469_231_731_687_303_715_884_105_727n, keys = (value, length) => Array.isArray(value) && value.length === length && value.every((key) => typeof key === "string" && key), global = snapshot?.globalConfig;
  return Number.isInteger(snapshot?.poolBump) && snapshot.poolBump >= 0 && snapshot.poolBump <= 255 && Number.isInteger(snapshot.poolIndex) && snapshot.poolIndex >= 0 && snapshot.poolIndex <= 65_535 && typeof snapshot.creator === "string" && snapshot.creator && typeof snapshot.coinCreator === "string" && snapshot.coinCreator && typeof snapshot.tokenMint0 === "string" && snapshot.tokenMint0 && typeof snapshot.tokenMint1 === "string" && snapshot.tokenMint1 && snapshot.tokenMint0 !== snapshot.tokenMint1 && typeof snapshot.lpMint === "string" && snapshot.lpMint && typeof snapshot.tokenVault0 === "string" && snapshot.tokenVault0 && typeof snapshot.tokenVault1 === "string" && snapshot.tokenVault1 && snapshot.tokenVault0 !== snapshot.tokenVault1 && typeof snapshot.vaultAuthority0 === "string" && snapshot.vaultAuthority0 && typeof snapshot.vaultAuthority1 === "string" && snapshot.vaultAuthority1 && [snapshot.lpSupplyRaw, snapshot.baseMintSupplyRaw, snapshot.vault0AmountRaw, snapshot.vault1AmountRaw].every(u64) && i128(snapshot.virtualQuoteReservesRaw) && BigInt(snapshot.vault1AmountRaw) + BigInt(snapshot.virtualQuoteReservesRaw) > 0n && typeof snapshot.canonicalPoolAuthority === "string" && snapshot.canonicalPoolAuthority && Number.isInteger(snapshot.canonicalPoolAuthorityBump) && snapshot.canonicalPoolAuthorityBump >= 0 && snapshot.canonicalPoolAuthorityBump <= 255 && snapshot.canonicalPumpPool === (snapshot.canonicalPoolAuthority === snapshot.creator) && typeof global?.admin === "string" && global.admin && [global.lpFeeBasisPoints, global.protocolFeeBasisPoints, global.coinCreatorFeeBasisPoints, global.buybackBasisPoints].every((value) => u64(value) && BigInt(value) <= 10_000n) && keys(global.protocolFeeRecipients, 8) && typeof global.reservedFeeRecipient === "string" && global.reservedFeeRecipient && keys(global.reservedFeeRecipients, 7) && keys(global.buybackFeeRecipients, 8) && [global.mayhemModeEnabled, global.isCashbackEnabled, global.boostEnabled].every((value) => typeof value === "boolean");
}

function completePumpCurveState(snapshot) {
  const u64 = (value) => typeof value === "string" && /^\d+$/.test(value) && BigInt(value) <= 18_446_744_073_709_551_615n;
  return typeof snapshot?.creator === "string" && snapshot.creator && [snapshot.baseMintSupplyRaw, snapshot.virtualTokenReservesRaw, snapshot.virtualQuoteReservesRaw, snapshot.realTokenReservesRaw, snapshot.realQuoteReservesRaw, snapshot.tokenTotalSupplyRaw].every(u64) && [snapshot.complete, snapshot.mayhemMode].every((value) => typeof value === "boolean") && /^[0-9a-f]{64}$/.test(snapshot.rawPayloadHash ?? "");
}

function latestPoolDependencySlot(snapshot) {
  const dependencySlots = [snapshot?.stateSlot, snapshot?.openOrdersSlot, snapshot?.marketSlot, snapshot?.balanceSlot, snapshot?.configSlot, snapshot?.mintSlot, snapshot?.tickArraySlot, snapshot?.binArraySlot, snapshot?.bitmapExtensionSlot, snapshot?.ammConfigSlot, snapshot?.feeConfigSlot, snapshot?.globalConfigSlot, snapshot?.mintEvidenceSlot].filter((slot) => Number.isSafeInteger(slot) && slot >= 0);
  return dependencySlots.length > 0 ? Math.max(...dependencySlots) : null;
}

function completePersistedPoolEnvelope(snapshot) {
  const dependencySlot = latestPoolDependencySlot(snapshot);
  return snapshot?.genesisHash === GENESIS_HASH && /^[0-9a-f]{64}$/.test(snapshot.sourceHash ?? "") && dependencySlot != null && snapshot.evidenceSlot === dependencySlot;
}

export function completeMeteoraBitmapExtension(snapshot) {
  const arrays = snapshot?.binArrays;
  if (!Array.isArray(arrays)) return false;
  const outside = arrays.filter((array) => Number.isInteger(array?.index) && (array.index < -512 || array.index >= 512));
  if (outside.length === 0) return snapshot.binArrayBitmapExtension == null && snapshot.binArrayBitmapExtensionSlot == null;
  const extension = snapshot.binArrayBitmapExtension, slot = snapshot.binArrayBitmapExtensionSlot;
  if (!validMeteoraBitmapExtension(extension, snapshot.address) || !Number.isSafeInteger(slot) || slot < snapshot.binArraySlot || slot > snapshot.balanceSlot) return false;
  const actual = new Set(arrays.map((array) => array.index));
  return outside.every((array) => extension.initializedBinArrayIndexes.includes(array.index)) && extension.initializedBinArrayIndexes.every((index) => actual.has(index));
}

function completeOrcaEconomics(snapshot) {
  const u64 = (value) => typeof value === "string" && /^\d+$/.test(value) && BigInt(value) <= 18_446_744_073_709_551_615n, u128 = (value) => typeof value === "string" && /^\d+$/.test(value) && BigInt(value) <= 340_282_366_920_938_463_463_374_607_431_768_211_455n;
  return typeof snapshot?.whirlpoolsConfig === "string" && snapshot.whirlpoolsConfig && typeof snapshot.tokenMint0 === "string" && snapshot.tokenMint0 && typeof snapshot.tokenMint1 === "string" && snapshot.tokenMint1 && snapshot.tokenMint0 !== snapshot.tokenMint1 && typeof snapshot.tokenVault0 === "string" && snapshot.tokenVault0 && typeof snapshot.tokenVault1 === "string" && snapshot.tokenVault1 && snapshot.tokenVault0 !== snapshot.tokenVault1 && [snapshot.vault0AmountRaw, snapshot.vault1AmountRaw, snapshot.protocolFeeOwed0Raw, snapshot.protocolFeeOwed1Raw].every(u64) && u128(snapshot.liquidityRaw) && u128(snapshot.sqrtPriceX64) && BigInt(snapshot.protocolFeeOwed0Raw) <= BigInt(snapshot.vault0AmountRaw) && BigInt(snapshot.protocolFeeOwed1Raw) <= BigInt(snapshot.vault1AmountRaw);
}

function completeOrcaTicks(snapshot) {
  const u128 = (value) => typeof value === "string" && /^\d+$/.test(value) && BigInt(value) <= 340_282_366_920_938_463_463_374_607_431_768_211_455n, i128 = (value) => typeof value === "string" && /^-?\d+$/.test(value) && BigInt(value) >= -170_141_183_460_469_231_731_687_303_715_884_105_728n && BigInt(value) <= 170_141_183_460_469_231_731_687_303_715_884_105_727n;
  return snapshot.tickArrays.every((array) => { const seen = new Set(); return array.initializedTicks.every((tick) => { const offset = (tick?.tick - array.startTickIndex) / snapshot.tickSpacing, valid = Number.isInteger(tick?.tick) && Number.isInteger(offset) && offset >= 0 && offset < 88 && !seen.has(tick.tick) && i128(tick.liquidityNetRaw) && u128(tick.liquidityGrossRaw) && BigInt(tick.liquidityGrossRaw) > 0n && u128(tick.feeGrowthOutside0X64) && u128(tick.feeGrowthOutside1X64) && Array.isArray(tick.rewardGrowthsOutsideX64) && tick.rewardGrowthsOutsideX64.length === 3 && tick.rewardGrowthsOutsideX64.every(u128); if (valid) seen.add(tick.tick); return valid; }); });
}

export function compileWarehouseBatch(state, checkpoint = { lastSequence: 0 }) {
  const lastSequence = Number(checkpoint?.lastSequence ?? 0);
  if (!Number.isSafeInteger(lastSequence) || lastSequence < 0) throw new Error("invalid warehouse checkpoint");
  if (!Number.isSafeInteger(state?.eventSequence) || !Array.isArray(state?.events)) throw new Error("invalid index event state");
  let previous = null;
  for (const event of state.events) { if (!Number.isSafeInteger(event?.sequence) || (previous != null && event.sequence !== previous + 1) || typeof event.type !== "string" || !event.type) throw new Error(previous != null && event?.sequence > previous + 1 ? "warehouse event sequence gap" : "invalid non-monotonic index event sequence"); if (!canonicalPersistedEvent(event)) throw new Error(`invalid warehouse event ${event.sequence}`); previous = event.sequence; }
  if (!canonicalPersistedEventLog(state.events, state.eventSequence, { programEvents: state.programEvents, swaps: state.swaps, blocks: state.blocks, holderSnapshots: state.holderSnapshots, poolSnapshots: state.poolSnapshots, mints: state.mints })) throw new Error("invalid warehouse event high-water mark");
  if (state.events.length && previous !== state.eventSequence) throw new Error("index event high-water mark mismatch");
  if (lastSequence > state.eventSequence) throw new Error("warehouse checkpoint is ahead of index");
  const oldest = state.events[0]?.sequence ?? state.eventSequence + 1;
  if (lastSequence < oldest - 1) throw new Error("warehouse checkpoint is older than retained replay history");
  const events = state.events.filter((event) => event.sequence > lastSequence);
  if (events.length && events[0].sequence !== lastSequence + 1) throw new Error("warehouse event sequence gap");
  const rows = events.map((event) => ({ chain: CHAIN, sequence: event.sequence, event_type: event.type, slot: event.slot, block_time: event.blockTime == null ? null : new Date(event.blockTime * 1_000).toISOString(), commitment: event.provenance?.commitment ?? "unknown", blockhash: event.blockhash ?? "", payload: JSON.stringify(event) }));
  return { fromSequence: lastSequence + 1, toSequence: events.at(-1)?.sequence ?? lastSequence, events: rows };
}

function factBase(row) {
  if (!Number.isSafeInteger(row?.slot) || row.slot < 0 || (row.blockTime != null && canonicalUnixSecondsToMilliseconds(row.blockTime) == null) || typeof row.signature !== "string" || !row.signature || !["confirmed", "finalized"].includes(row.provenance?.commitment)) throw new Error("invalid canonical warehouse fact");
  return { chain: CHAIN, slot: row.slot, block_time: row.blockTime == null ? null : new Date(row.blockTime * 1_000).toISOString(), signature: row.signature, commitment: row.provenance.commitment };
}

function withFactContentHash(kind, row) { return { ...row, content_hash: projectionContentHash(`clickhouse-${kind}-v1`, row) }; }

export function compileWarehouseFacts(state, batch) {
  if (state?.checkpoints?.deadLetterOverflow != null) throw new Error("dead-letter capacity exceeded; warehouse publication refused");
  if (!canonicalPersistedInstructionLog(state?.instructions, state?.transactions, state?.blocks)) throw new Error("invalid persisted instruction evidence");
  if (!canonicalPersistedSwapLog(state?.swaps, state?.transactions, state?.blocks)) throw new Error("invalid persisted swap evidence");
  if (!canonicalPersistedDerivedLedger({ ...state, instructions: state?.instructions })) throw new Error("invalid persisted derived ledger evidence");
  const slots = [...new Set(batch.events.map((event) => event.slot))].sort((a, b) => a - b), selected = (rows) => (rows ?? []).filter((row) => slots.includes(row.slot));
  const identities = new Set(), unique = (identity) => { if (identities.has(identity)) throw new Error(`duplicate canonical warehouse fact ${identity}`); identities.add(identity); };
  const instructions = selected(state.instructions).map((row) => { const base = factBase(row); if (!Number.isInteger(row.instructionIndex) || row.instructionIndex < 0 || (row.innerIndex != null && (!Number.isInteger(row.innerIndex) || row.innerIndex < 0)) || typeof row.eventId !== "string" || !row.eventId || typeof row.programId !== "string" || !row.programId || !Array.isArray(row.accounts) || !/^([0-9a-f]{64})$/.test(row.rawPayloadHash ?? "")) throw new Error("invalid canonical instruction fact"); unique(`instruction:${row.eventId}`); return withFactContentHash("instruction", { ...base, event_id: row.eventId, instruction_index: row.instructionIndex, inner_index: row.innerIndex, program_id: row.programId, protocol: row.protocol ?? null, registry_version: row.registryVersion, decoder_version: row.decoderVersion ?? null, parsed_type: row.parsedType ?? null, accounts: row.accounts, data: row.data ?? null, raw_payload_hash: row.rawPayloadHash, payload: JSON.stringify(row) }); });
  const swaps = selected(state.swaps).map((row) => { const base = factBase(row); if (typeof row.swapId !== "string" || !row.swapId || !Number.isInteger(row.eventIndex) || row.eventIndex < 0 || !row.pool || !row.protocol || !row.baseMint || !row.quoteMint || !row.inputMint || !row.outputMint || !/^\d+$/.test(row.inputAmountRaw ?? "") || !/^\d+$/.test(row.outputAmountRaw ?? "") || (row.tradeFeeRaw != null && !/^\d+$/.test(row.tradeFeeRaw)) || !/^([0-9a-f]{64})$/.test(row.rawPayloadHash ?? "")) throw new Error("invalid canonical swap fact"); unique(`swap:${row.swapId}`); return withFactContentHash("swap", { ...base, swap_id: row.swapId, event_index: row.eventIndex, pool: row.pool, protocol: row.protocol, base_mint: row.baseMint, quote_mint: row.quoteMint, input_mint: row.inputMint, output_mint: row.outputMint, input_amount_raw: row.inputAmountRaw, output_amount_raw: row.outputAmountRaw, trade_fee_raw: row.tradeFeeRaw ?? null, decoder_version: row.decoderVersion ?? null, raw_payload_hash: row.rawPayloadHash, payload: JSON.stringify(row) }); });
  const balanceChanges = selected(state.balanceChanges).map((row) => { const base = factBase(row); if (!Number.isInteger(row.accountIndex) || row.accountIndex < 0 || !row.tokenAccount || !row.mint || !Number.isInteger(row.decimals) || row.decimals < 0 || row.decimals > 255 || !/^\d+$/.test(row.preAmountRaw ?? "") || !/^\d+$/.test(row.postAmountRaw ?? "") || typeof row.closed !== "boolean") throw new Error("invalid canonical balance fact"); unique(`balance:${row.signature}:${row.accountIndex}`); return withFactContentHash("balance", { ...base, account_index: row.accountIndex, token_account: row.tokenAccount, owner: row.owner ?? null, program_id: row.programId ?? null, mint: row.mint, decimals: row.decimals, pre_amount_raw: row.preAmountRaw, post_amount_raw: row.postAmountRaw, closed: row.closed ? 1 : 0, payload: JSON.stringify(row) }); });
  const nativeTransfers = selected(state.nativeTransfers).map((row) => { const base = factBase(row), systemProgram = "11111111111111111111111111111111", stakeProgram = "Stake11111111111111111111111111111111111111", accountCreation = ["account_creation", "seeded_account_creation", "prefunded_account_creation"].includes(row.transferKind), seeded = ["seeded_account_creation", "seeded_transfer"].includes(row.transferKind); if (typeof row.transferId !== "string" || !row.transferId || !Number.isInteger(row.instructionIndex) || row.instructionIndex < 0 || (row.innerIndex != null && (!Number.isInteger(row.innerIndex) || row.innerIndex < 0)) || !((row.programId === systemProgram && ["transfer", "seeded_transfer", "account_creation", "seeded_account_creation", "prefunded_account_creation", "nonce_withdrawal"].includes(row.transferKind)) || (row.programId === stakeProgram && row.transferKind === "stake_withdrawal")) || typeof row.source !== "string" || !row.source || typeof row.destination !== "string" || !row.destination || !/^\d+$/.test(row.lamportsRaw ?? "") || BigInt(row.lamportsRaw) > 18_446_744_073_709_551_615n || (accountCreation && (!/^\d+$/.test(row.allocatedSpaceRaw ?? "") || BigInt(row.allocatedSpaceRaw) > 18_446_744_073_709_551_615n || typeof row.ownerProgram !== "string" || !row.ownerProgram)) || (!accountCreation && row.allocatedSpaceRaw != null) || (seeded && (typeof row.baseAddress !== "string" || !row.baseAddress || typeof row.seed !== "string" || row.seed.length > 32 || [...row.seed].some((character) => character.charCodeAt(0) > 0x7f) || typeof row.ownerProgram !== "string" || !row.ownerProgram)) || (!seeded && (row.baseAddress != null || row.seed != null)) || (!accountCreation && !seeded && row.ownerProgram != null) || ![3, 4, 5, 6, 7].includes(row.decoderVersion) || !/^([0-9a-f]{64})$/.test(row.rawPayloadHash ?? "")) throw new Error("invalid canonical native transfer fact"); unique(`native-transfer:${row.transferId}`); return withFactContentHash("native-transfer", { ...base, transfer_id: row.transferId, instruction_index: row.instructionIndex, inner_index: row.innerIndex, program_id: row.programId, transfer_kind: row.transferKind, source: row.source, destination: row.destination, lamports_raw: row.lamportsRaw, allocated_space_raw: row.allocatedSpaceRaw, owner_program: row.ownerProgram, base_address: row.baseAddress, seed: row.seed, decoder_version: row.decoderVersion, raw_payload_hash: row.rawPayloadHash, payload: JSON.stringify(row) }); });
  const deadLetters = (state.deadLetters ?? []).map((row) => { const observedAt = row.lastObservedAt ?? row.firstObservedAt, observed = parseCanonicalUtcTimestamp(observedAt); if (typeof row.id !== "string" || !row.id || typeof row.filename !== "string" || !row.filename || (row.fingerprint != null && !/^[0-9a-f]{64}$/.test(row.fingerprint)) || typeof row.error !== "string" || !row.error || !Number.isSafeInteger(row.attempts) || row.attempts < 1 || observed == null || typeof row.resolved !== "boolean") throw new Error("invalid canonical dead-letter fact"); unique(`dead-letter:${row.id}`); return withFactContentHash("dead-letter", { chain: CHAIN, observed_at: observedAt, source: row.filename, identity: row.id, payload_hash: row.fingerprint ?? null, error: row.error, attempts: row.attempts, resolved: row.resolved ? 1 : 0, resolution: row.resolution ?? null, payload: JSON.stringify(row) }); });
  const candleProjection = compileWarehouseCandles(state, batch);
  return { slots, instructions, swaps, balanceChanges, nativeTransfers, deadLetters, ...candleProjection };
}

function candleAmounts(swap) {
  const base = swap.inputMint === swap.baseMint ? swap.inputAmountRaw : swap.outputMint === swap.baseMint ? swap.outputAmountRaw : null;
  const quote = swap.inputMint === swap.quoteMint ? swap.inputAmountRaw : swap.outputMint === swap.quoteMint ? swap.outputAmountRaw : null;
  if (!/^\d+$/.test(base ?? "") || !/^\d+$/.test(quote ?? "") || BigInt(base) === 0n) return null;
  return { base, quote };
}

export function compileWarehouseCandles(state, batch, intervals = CANDLE_INTERVALS) {
  if (!Array.isArray(intervals) || !intervals.length || intervals.some((value) => !Number.isSafeInteger(value) || value < 1) || new Set(intervals).size !== intervals.length) throw new Error("invalid warehouse candle intervals");
  const affected = new Map(), sourceSequence = (batch.events ?? []).reduce((value, event) => Math.max(value, event.sequence ?? -1), -1);
  if ((batch.events ?? []).length && (!Number.isSafeInteger(sourceSequence) || sourceSequence < 0)) throw new Error("invalid warehouse candle source sequence");
  for (const event of batch.events ?? []) {
    let payload; try { payload = JSON.parse(event.payload); } catch { throw new Error(`invalid warehouse candle event ${event.sequence}`); }
    for (const swap of [...(payload.swaps ?? []), ...(payload.revertedSwaps ?? [])]) {
      if (!swap?.pool || !Number.isSafeInteger(swap.blockTime) || swap.blockTime < 0) throw new Error("invalid warehouse candle source");
      for (const interval of intervals) { const bucket = Math.floor(swap.blockTime / interval) * interval, key = `${swap.pool}\u0000${interval}\u0000${bucket}`; affected.set(key, { pool: swap.pool, interval, bucket }); }
    }
  }
  const compare = (left, right) => { const a = BigInt(left.n) * BigInt(right.d), b = BigInt(right.n) * BigInt(left.d); return a === b ? 0 : a < b ? -1 : 1; };
  const candles = [];
  for (const key of [...affected.keys()].sort()) {
    const target = affected.get(key), candidates = (state.swaps ?? []).filter((swap) => swap.pool === target.pool && Number.isSafeInteger(swap.blockTime) && Math.floor(swap.blockTime / target.interval) * target.interval === target.bucket).sort((a, b) => a.blockTime - b.blockTime || a.slot - b.slot || a.eventIndex - b.eventIndex), row = { schema_version: 1, source_sequence: sourceSequence, chain: CHAIN, pool: target.pool, interval_seconds: target.interval, bucket_start: new Date(target.bucket * 1_000).toISOString(), base_mint: null, quote_mint: null, base_decimals: null, quote_decimals: null, open_numerator_raw: null, open_denominator_raw: null, high_numerator_raw: null, high_denominator_raw: null, low_numerator_raw: null, low_denominator_raw: null, close_numerator_raw: null, close_denominator_raw: null, base_volume_raw: 0n, quote_volume_raw: 0n, trades: 0, first_slot: null, last_slot: null, commitment: "finalized" };
    for (const swap of candidates) {
      const amounts = candleAmounts(swap); if (!amounts) continue;
      const pair = `${swap.baseMint}\u0000${swap.quoteMint}`; if (row.base_mint != null && pair !== `${row.base_mint}\u0000${row.quote_mint}`) throw new Error(`conflicting canonical candle pair ${target.pool}`);
      const price = { n: amounts.quote, d: amounts.base }; row.base_mint ??= swap.baseMint; row.quote_mint ??= swap.quoteMint; row.base_decimals ??= swap.baseDecimals ?? null; row.quote_decimals ??= swap.quoteDecimals ?? null;
      if (row.trades === 0) { row.open_numerator_raw = row.high_numerator_raw = row.low_numerator_raw = price.n; row.open_denominator_raw = row.high_denominator_raw = row.low_denominator_raw = price.d; row.first_slot = swap.slot; }
      if (compare(price, { n: row.high_numerator_raw, d: row.high_denominator_raw }) > 0) { row.high_numerator_raw = price.n; row.high_denominator_raw = price.d; }
      if (compare(price, { n: row.low_numerator_raw, d: row.low_denominator_raw }) < 0) { row.low_numerator_raw = price.n; row.low_denominator_raw = price.d; }
      row.close_numerator_raw = price.n; row.close_denominator_raw = price.d; row.base_volume_raw += BigInt(amounts.base); row.quote_volume_raw += BigInt(amounts.quote); row.trades++; row.last_slot = swap.slot; if (swap.provenance?.commitment !== "finalized") row.commitment = "confirmed";
    }
    if (row.trades) candles.push({ ...row, base_volume_raw: row.base_volume_raw.toString(), quote_volume_raw: row.quote_volume_raw.toString() });
  }
  return { candleKeys: [...affected.values()].sort((a, b) => a.pool.localeCompare(b.pool) || a.interval - b.interval || a.bucket - b.bucket), candles };
}

export function checkpointSql(sequence) {
  if (!Number.isSafeInteger(sequence) || sequence < 0) throw new Error("invalid warehouse sequence");
  return `INSERT INTO ingestion_checkpoints (consumer, chain, genesis_hash, slot, cursor, schema_version) VALUES ('warehouse-canonical-events', ${sqlLiteral(CHAIN)}, ${sqlLiteral(GENESIS_HASH)}, ${sequence}, ${sqlLiteral(String(sequence))}, 1) ON CONFLICT (consumer) DO UPDATE SET chain = EXCLUDED.chain, genesis_hash = EXCLUDED.genesis_hash, slot = EXCLUDED.slot, cursor = EXCLUDED.cursor, schema_version = EXCLUDED.schema_version, updated_at = now();\n`;
}

function jsonbLiteral(value) { return `${sqlLiteral(JSON.stringify(value))}::jsonb`; }

function projectionContentHash(label, value) { return crypto.createHash("sha256").update(`${label}:${JSON.stringify(value)}`).digest("hex"); }

function warehouseTokenProjection(state, mint, row) {
  const info = row?.mintInfo ?? null, decimals = info?.decimals ?? null, sourceSlot = row?.authoritySourceSlot ?? row?.lastSlot ?? null, transferCount = row?.transferCount ?? 0, swapCount = row?.swapCount ?? 0, lastSlot = row?.lastSlot ?? null, lastBlockTime = row?.lastBlockTime ?? null;
  if (!mint || /[\u0000-\u001f]/.test(mint) || (decimals != null && (!Number.isInteger(decimals) || decimals < 0 || decimals > 255)) || (sourceSlot != null && (!Number.isSafeInteger(sourceSlot) || sourceSlot < 0)) || !Number.isSafeInteger(transferCount) || transferCount < 0 || !Number.isSafeInteger(swapCount) || swapCount < 0 || (lastSlot != null && (!Number.isSafeInteger(lastSlot) || lastSlot < 0)) || (lastBlockTime != null && (!Number.isSafeInteger(lastBlockTime) || lastBlockTime < 0))) throw new Error(`invalid warehouse mint metadata ${mint}`);
  const canonicalMetadata = row?.metadata ?? null, tokenMetadataValid = canonicalMetadata == null || isCanonicalTokenMetadata(canonicalMetadata, mint), offchainMetadataValid = row?.offchainMetadata == null || tokenMetadataValid && canonicalMetadata != null && isCanonicalOffchainTokenMetadata(row.offchainMetadata, canonicalMetadata.uri), metadata = { transferCount, swapCount, lastSlot, lastBlockTime, tokenMetadata: tokenMetadataValid ? canonicalMetadata : null, tokenMetadataQuarantined: !tokenMetadataValid, metadataEvidence: metadataEvidenceProjection(state, mint), offchainTokenMetadata: offchainMetadataValid ? row?.offchainMetadata ?? null : null, offchainTokenMetadataQuarantined: !offchainMetadataValid }, authorities = { mintAuthority: info?.mintAuthority ?? null, freezeAuthority: info?.freezeAuthority ?? null }, extensions = Array.isArray(info?.extensions) ? info.extensions : [];
  const contentHash = projectionContentHash("warehouse-token-v1", { decimals, metadata, authorities, extensions, sourceSlot }); return { decimals, metadata, authorities, extensions, sourceSlot, contentHash };
}

function respCommand(parts) { const chunks = [Buffer.from(`*${parts.length}\r\n`)]; for (const part of parts) { const value = Buffer.from(String(part)); chunks.push(Buffer.from(`$${value.length}\r\n`), value, Buffer.from("\r\n")); } return Buffer.concat(chunks); }

function redisJson(value, label) { let encoded; try { encoded = JSON.stringify(value); } catch { throw new Error(`invalid Redis ${label} payload`); } if (typeof encoded !== "string") throw new Error(`invalid Redis ${label} payload`); return encoded; }

function redisHotTokenRow(state, mint, row) { return { ...row, metadataEvidence: metadataEvidenceProjection(state, mint) }; }

function redisHotStatsRow(state) { return { chain: CHAIN, genesisHash: GENESIS_HASH, tip: state.tip ?? null, eventSequence: state.eventSequence, pools: Object.keys(state.pools).length, tokens: Object.keys(state.mints).length, updatedAt: state.updatedAt ?? null }; }

export function compileRedisHotSync(state, batch, ttlSeconds = 86_400, maxBytes = 16_777_216) {
  if (!canonicalAggregateProjections(state)) throw new Error("invalid persisted aggregate projections");
  if (!canonicalPersistedProgramEventLog(state?.programEvents, state?.swaps, state?.transactions, state?.blocks)) throw new Error("invalid persisted program event evidence");
  if (!canonicalSnapshotProjections(state)) throw new Error("invalid persisted snapshot projections");
  if (!canonicalMetadataProjections(state)) throw new Error("invalid persisted metadata projections");
  if (!Number.isInteger(ttlSeconds) || ttlSeconds < 300 || !Number.isInteger(maxBytes) || maxBytes < 65_536 || !Number.isSafeInteger(batch?.toSequence) || batch.toSequence < 0 || !Array.isArray(batch?.events) || !state?.pools || typeof state.pools !== "object" || Array.isArray(state.pools) || !state?.mints || typeof state.mints !== "object" || Array.isArray(state.mints) || (state.updatedAt != null && parseCanonicalUtcTimestamp(state.updatedAt) == null)) throw new Error("invalid Redis hot-state configuration");
  const version = batch.toSequence, prefix = `terminal_dex:hot:${version}`, poolKey = `${prefix}:pools`, tokenKey = `${prefix}:tokens`, commands = [respCommand(["MULTI"]), respCommand(["DEL", poolKey, tokenKey])];
  for (const [address, row] of Object.entries(state.pools).sort(([left], [right]) => left.localeCompare(right))) { if (!address || /[\u0000-\u001f]/.test(address)) throw new Error("invalid Redis pool identity"); commands.push(respCommand(["HSET", poolKey, address, redisJson(row, "pool")])); }
  for (const [mint, row] of Object.entries(state.mints).sort(([left], [right]) => left.localeCompare(right))) { if (!mint || /[\u0000-\u001f]/.test(mint)) throw new Error("invalid Redis mint identity"); commands.push(respCommand(["HSET", tokenKey, mint, redisJson(redisHotTokenRow(state, mint, row), "mint")])); }
  commands.push(respCommand(["SET", "terminal_dex:hot:current", String(version)]), respCommand(["SET", `${prefix}:stats`, redisJson(redisHotStatsRow(state), "stats")]), respCommand(["EXPIRE", poolKey, ttlSeconds]), respCommand(["EXPIRE", tokenKey, ttlSeconds]), respCommand(["EXPIRE", `${prefix}:stats`, ttlSeconds]));
  for (const event of batch.events) { if (typeof event?.payload !== "string") throw new Error("invalid Redis event payload"); commands.push(respCommand(["PUBLISH", "terminal_dex:canonical_events", event.payload])); } commands.push(respCommand(["EXEC"])); const payload = Buffer.concat(commands); if (payload.length > maxBytes) throw new Error("Redis hot-state batch exceeds configured byte limit"); return payload;
}

export function compileWarehouseProjections(store, staleAfterMs = 120_000, limit = 500) {
  if (!canonicalPersistedProgramEventLog(store?.state?.programEvents, store?.state?.swaps, store?.state?.transactions, store?.state?.blocks)) throw new Error("invalid persisted program event evidence");
  const blocks = Object.values(store?.state?.blocks ?? {}); if (blocks.some((row) => !Number.isSafeInteger(row?.blockTime) || row.blockTime < 0)) throw new Error("invalid warehouse projection context"); const blockTimes = blocks.map((row) => row.blockTime * 1_000), now = blockTimes.length ? blockTimes.reduce((latest, value) => Math.max(latest, value), 0) : parseCanonicalUtcTimestamp(store?.state?.updatedAt); if (now == null || !Number.isSafeInteger(now) || !Number.isInteger(staleAfterMs) || staleAfterMs < 1_000 || !Number.isInteger(limit) || limit < 1 || limit > 10_000) throw new Error("invalid warehouse projection context");
  const candidates = store.trending(limit, 86_400, now).map((row) => { if (!row.mint || !Number.isSafeInteger(row.swapCount) || row.swapCount < 0 || !Number.isSafeInteger(row.uniqueTraders) || row.uniqueTraders < 0 || !Number.isSafeInteger(row.transferCount) || row.transferCount < 0) throw new Error("invalid warehouse candidate projection"); const score = row.swapCount * 1_000_000 + row.uniqueTraders * 1_000 + row.transferCount; if (!Number.isSafeInteger(score)) throw new Error("warehouse candidate score overflow"); return { mint: row.mint, scoreVersion: "activity-v1", score, state: "review_required", evidence: { schemaVersion: 1, asOf: new Date(now).toISOString(), windowSeconds: 86_400, activity: row, automationSafe: false } }; });
  const security = Object.keys(store.state.mints).sort().map((mint) => store.tokenSecurity(mint, staleAfterMs, now)).filter((row) => row.evidence?.slot != null).map((row) => { if (!row.mint || row.ruleVersion !== "token-security-v1" || !Number.isSafeInteger(row.evidence.slot) || row.evidence.slot < 0 || !Array.isArray(row.findings)) throw new Error("invalid warehouse security projection"); const blocking = !row.assessable || row.findings.some((finding) => finding.blocksAutomation), severity = row.findings.some((finding) => finding.severity === "high") ? "high" : row.findings.some((finding) => finding.severity === "medium") ? "medium" : row.assessable ? "low" : "unknown"; return { mint: row.mint, ruleVersion: row.ruleVersion, sourceSlot: row.evidence.slot, severity, blocksResearch: false, blocksEntry: blocking, blocksExit: false, observedAt: new Date(now).toISOString(), expiresAt: new Date(now + staleAfterMs).toISOString(), evidence: row }; });
  const stale = (observedAt) => { const observed = parseCanonicalUtcTimestamp(observedAt); return observed == null || observed > now || now - observed > staleAfterMs; }, jobs = [], tokenPrograms = new Set(["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"]);
  for (const mint of Object.keys(store.state.mints).sort()) { const snapshot = store.state.holderSnapshots[mint], incomplete = snapshot && !isCanonicalAccountSnapshotEvidence(snapshot, store.state.mints[mint]?.mintInfo), metadataSearchIncomplete = snapshot && !incomplete && snapshot.metadataSearchComplete !== true; if (!snapshot || incomplete || metadataSearchIncomplete || stale(snapshot.observedAt)) jobs.push({ key: `account-snapshot:${mint}`, type: "account_snapshot", payload: { schemaVersion: 1, chain: CHAIN, mint, reason: !snapshot ? "missing" : incomplete ? "incomplete_account_evidence" : metadataSearchIncomplete ? "metadata_search_incomplete" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: snapshot?.slot ?? null } }); }
  for (const [mint, row] of Object.entries(store.state.mints).sort(([left], [right]) => left.localeCompare(right))) { const canonical = row.metadata, enriched = row.offchainMetadata, incomplete = enriched && !isCanonicalOffchainTokenMetadata(enriched, canonical?.uri), observed = parseCanonicalUtcTimestamp(enriched?.observedAt), enrichmentAge = observed == null ? null : now - observed, refresh = !enriched || incomplete || enrichmentAge == null || enrichmentAge < 0 || enrichmentAge > 86_400_000; if (isCanonicalTokenMetadata(canonical, mint) && canonical.uri.startsWith("https://") && refresh) jobs.push({ key: `offchain-metadata-snapshot:${mint}`, type: "offchain_metadata_snapshot", payload: { schemaVersion: 1, chain: CHAIN, mint, uri: canonical.uri, onchainMetadataHash: canonical.rawPayloadHash, reason: !enriched ? "missing" : incomplete ? "incomplete_metadata_evidence" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: row.authoritySourceSlot ?? row.lastSlot ?? null } }); }
  const completeClmmQuoteEvidence = (snapshot) => completePersistedPoolEnvelope(snapshot) && snapshot?.programId === RAYDIUM_CLMM_PROGRAM && typeof snapshot.address === "string" && snapshot.address && snapshot?.commitment === "finalized" && Number.isSafeInteger(snapshot.stateSlot) && Number.isSafeInteger(snapshot.balanceSlot) && snapshot.stateSlot <= snapshot.balanceSlot && snapshot.tickArrayCoverage === "finalized_program_account_snapshot" && Number.isSafeInteger(snapshot.tickArraySlot) && snapshot.tickArraySlot >= snapshot.stateSlot && snapshot.tickArraySlot <= snapshot.balanceSlot && Number.isSafeInteger(snapshot.ammConfigSlot) && snapshot.ammConfigSlot >= snapshot.stateSlot && snapshot.ammConfigSlot <= snapshot.balanceSlot && typeof snapshot.ammConfig === "string" && snapshot.ammConfig && snapshot.ammConfigState?.address === snapshot.ammConfig && Number.isInteger(snapshot.tickSpacing) && snapshot.tickSpacing > 0 && snapshot.ammConfigState?.tickSpacing === snapshot.tickSpacing && validateBoundPoolMintEvidence(snapshot, snapshot.balanceSlot) && completeClmmEconomics(snapshot) && completeClmmTickCoverage(snapshot) && /^[0-9a-f]{64}$/.test(snapshot.rawPayloadHash ?? "") && /^[0-9a-f]{64}$/.test(snapshot.ammConfigState?.rawPayloadHash ?? "") && Number.isInteger(snapshot.ammConfigState?.tradeFeeRate) && snapshot.ammConfigState.tradeFeeRate >= 0 && snapshot.ammConfigState.tradeFeeRate < 1_000_000 && Number.isInteger(snapshot.status) && snapshot.status >= 0 && snapshot.status <= 255 && [0, 1, 2].includes(snapshot.feeOn) && typeof snapshot.dynamicFeeEnabled === "boolean";
  for (const [pool, row] of Object.entries(store.state.pools).sort(([left], [right]) => left.localeCompare(right))) if (row.protocol === "raydium-clmm") { const snapshot = row.accountSnapshot, incomplete = snapshot && (snapshot.address !== pool || !completeClmmQuoteEvidence(snapshot)); if (!snapshot || incomplete || stale(snapshot.observedAt)) jobs.push({ key: `clmm-pool-snapshot:${pool}`, type: "clmm_pool_snapshot", payload: { schemaVersion: 1, chain: CHAIN, pool, reason: !snapshot ? "missing" : incomplete ? "incomplete_quote_evidence" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: latestPoolDependencySlot(snapshot) } }); }
  const completeCpmmQuoteEvidence = (snapshot) => completePersistedPoolEnvelope(snapshot) && snapshot?.programId === RAYDIUM_CPMM_PROGRAM && typeof snapshot.address === "string" && snapshot.address && snapshot?.commitment === "finalized" && Number.isSafeInteger(snapshot.stateSlot) && Number.isSafeInteger(snapshot.configSlot) && Number.isSafeInteger(snapshot.balanceSlot) && snapshot.stateSlot <= snapshot.configSlot && snapshot.configSlot <= snapshot.balanceSlot && snapshot.ammConfigSlot === snapshot.configSlot && typeof snapshot.ammConfig === "string" && snapshot.ammConfig && snapshot.ammConfigState?.address === snapshot.ammConfig && typeof snapshot.tokenProgram0 === "string" && typeof snapshot.tokenProgram1 === "string" && validateBoundPoolMintEvidence(snapshot, snapshot.balanceSlot) && completeCpmmEconomics(snapshot) && Number.isInteger(snapshot.status) && snapshot.status >= 0 && snapshot.status <= 255 && [0, 1, 2].includes(snapshot.creatorFeeOn) && typeof snapshot.enableCreatorFee === "boolean" && /^[0-9a-f]{64}$/.test(snapshot.rawPayloadHash ?? "") && /^[0-9a-f]{64}$/.test(snapshot.ammConfigState?.rawPayloadHash ?? "");
  for (const [pool, row] of Object.entries(store.state.pools).sort(([left], [right]) => left.localeCompare(right))) if (row.protocol === "raydium-cpmm") { const snapshot = row.accountSnapshot, incomplete = snapshot && (snapshot.address !== pool || !completeCpmmQuoteEvidence(snapshot)); if (!snapshot || incomplete || stale(snapshot.observedAt)) jobs.push({ key: `cpmm-pool-snapshot:${pool}`, type: "cpmm_pool_snapshot", payload: { schemaVersion: 1, chain: CHAIN, pool, reason: !snapshot ? "missing" : incomplete ? "incomplete_quote_evidence" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: latestPoolDependencySlot(snapshot) } }); }
  for (const [pool, row] of Object.entries(store.state.pools).sort(([left], [right]) => left.localeCompare(right))) if (row.protocol === "raydium-amm-v4") { const snapshot = row.accountSnapshot, incomplete = snapshot && (snapshot.address !== pool || !completeAmmV4Evidence(snapshot)); if (!snapshot || incomplete || stale(snapshot.observedAt)) jobs.push({ key: `amm-v4-pool-snapshot:${pool}`, type: "amm_v4_pool_snapshot", payload: { schemaVersion: 1, chain: CHAIN, pool, reason: !snapshot ? "missing" : incomplete ? "incomplete_state_evidence" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: latestPoolDependencySlot(snapshot) } }); }
  const completePumpSwapEvidence = (snapshot) => completePersistedPoolEnvelope(snapshot) && snapshot?.programId === PUMP_SWAP_PROGRAM && typeof snapshot.address === "string" && snapshot.address && snapshot?.commitment === "finalized" && Number.isSafeInteger(snapshot.stateSlot) && Number.isSafeInteger(snapshot.balanceSlot) && Number.isSafeInteger(snapshot.configSlot) && snapshot.stateSlot <= snapshot.balanceSlot && snapshot.balanceSlot <= snapshot.configSlot && snapshot.feeConfigSlot === snapshot.configSlot && snapshot.globalConfigSlot === snapshot.configSlot && snapshot.feeConfig?.address === PUMP_SWAP_FEE_CONFIG && snapshot.globalConfig?.address === PUMP_SWAP_GLOBAL_CONFIG && tokenPrograms.has(snapshot.tokenProgram0) && tokenPrograms.has(snapshot.tokenProgram1) && validateBoundPoolMintEvidence(snapshot, snapshot.configSlot) && completePumpSwapState(snapshot) && typeof snapshot.canonicalPumpPool === "boolean" && completePumpFeeConfig(snapshot.feeConfig, snapshot.canonicalPumpPool) && typeof snapshot.mayhemMode === "boolean" && typeof snapshot.cashbackCoin === "boolean" && Number.isInteger(snapshot.globalConfig?.disableFlags) && snapshot.globalConfig.disableFlags >= 0 && snapshot.globalConfig.disableFlags <= 31 && /^[0-9a-f]{64}$/.test(snapshot.rawPayloadHash ?? "") && /^[0-9a-f]{64}$/.test(snapshot.feeConfig?.rawPayloadHash ?? "") && /^[0-9a-f]{64}$/.test(snapshot.globalConfig?.rawPayloadHash ?? "");
  for (const [pool, row] of Object.entries(store.state.pools).sort(([left], [right]) => left.localeCompare(right))) if (row.protocol === "pump-swap") { const snapshot = row.accountSnapshot, incomplete = snapshot && (snapshot.address !== pool || !completePumpSwapEvidence(snapshot)); if (!snapshot || incomplete || stale(snapshot.observedAt)) jobs.push({ key: `pump-swap-pool-snapshot:${pool}`, type: "pump_swap_pool_snapshot", payload: { schemaVersion: 1, chain: CHAIN, pool, reason: !snapshot ? "missing" : incomplete ? "incomplete_execution_evidence" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: latestPoolDependencySlot(snapshot) } }); }
  const completePumpExecutionEvidence = (snapshot) => { const expectedQuoteMint = snapshot?.quoteMint === "11111111111111111111111111111111" ? "So11111111111111111111111111111111111111112" : snapshot?.quoteMint, adapter = { ...snapshot, tokenMint0: snapshot?.mint, tokenMint1: expectedQuoteMint, tokenProgram0: snapshot?.baseTokenProgram, tokenProgram1: snapshot?.quoteTokenProgram, mintDecimals0: snapshot?.baseDecimals, mintDecimals1: snapshot?.quoteDecimals }, canonicalCurve = (() => { try { return derivePumpBondingCurve(snapshot?.mint).address; } catch { return null; } })(), usesSolFees = expectedQuoteMint === "So11111111111111111111111111111111111111112"; return completePersistedPoolEnvelope(snapshot) && snapshot?.programId === PUMP_PROGRAM && snapshot.address === canonicalCurve && snapshot?.commitment === "finalized" && Number.isSafeInteger(snapshot.stateSlot) && Number.isSafeInteger(snapshot.mintSlot) && Number.isSafeInteger(snapshot.configSlot) && snapshot.stateSlot <= snapshot.mintSlot && snapshot.mintSlot <= snapshot.configSlot && tokenPrograms.has(snapshot.baseTokenProgram) && tokenPrograms.has(snapshot.quoteTokenProgram) && snapshot.executionQuoteMint === expectedQuoteMint && validateBoundPoolMintEvidence(adapter, snapshot.configSlot) && completePumpCurveState(snapshot) && typeof snapshot.cashbackCoin === "boolean" && snapshot.global?.address === PUMP_GLOBAL && completePumpGlobal(snapshot.global) && snapshot.feeConfig?.address === PUMP_FEE_CONFIG && snapshot.feeConfig?.bump === 253 && completePumpFeeConfig(snapshot.feeConfig, usesSolFees, !usesSolFees) && /^[0-9a-f]{64}$/.test(snapshot.global?.rawPayloadHash ?? "") && /^[0-9a-f]{64}$/.test(snapshot.feeConfig?.rawPayloadHash ?? ""); };
  const scheduledPumpMints = new Set(); for (const row of Object.values(store.state.pools)) if (row.protocol === "pump-bonding-curve" && row.baseMint && !scheduledPumpMints.has(row.baseMint)) { const snapshot = row.accountSnapshot, incomplete = snapshot && (snapshot.mint !== row.baseMint || !completePumpExecutionEvidence(snapshot)); if (!snapshot || incomplete || stale(snapshot.observedAt)) { scheduledPumpMints.add(row.baseMint); jobs.push({ key: `pump-bonding-curve-snapshot:${row.baseMint}`, type: "pump_bonding_curve_snapshot", payload: { schemaVersion: 1, chain: CHAIN, mint: row.baseMint, reason: !snapshot ? "missing" : incomplete ? "incomplete_execution_evidence" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: latestPoolDependencySlot(snapshot) } }); } }
  const completeOrcaQuoteEvidence = (snapshot) => completePersistedPoolEnvelope(snapshot) && snapshot?.programId === ORCA_WHIRLPOOL_PROGRAM && typeof snapshot.address === "string" && snapshot.address && snapshot.commitment === "finalized" && Number.isSafeInteger(snapshot.stateSlot) && Number.isSafeInteger(snapshot.tickArraySlot) && Number.isSafeInteger(snapshot.balanceSlot) && snapshot.stateSlot <= snapshot.tickArraySlot && snapshot.tickArraySlot <= snapshot.balanceSlot && snapshot.tickArrayCoverage === "finalized_program_account_snapshot" && Array.isArray(snapshot.tickArrays) && snapshot.tickArrays.length <= 2_048 && new Set(snapshot.tickArrays.map((array) => array?.address)).size === snapshot.tickArrays.length && new Set(snapshot.tickArrays.map((array) => array?.startTickIndex)).size === snapshot.tickArrays.length && tokenPrograms.has(snapshot.tokenProgram0) && tokenPrograms.has(snapshot.tokenProgram1) && validateBoundPoolMintEvidence(snapshot, snapshot.balanceSlot) && completeOrcaEconomics(snapshot) && Number.isInteger(snapshot.tickSpacing) && snapshot.tickSpacing > 0 && Number.isInteger(snapshot.tick) && snapshot.tick >= -443_636 && snapshot.tick <= 443_636 && Number.isInteger(snapshot.feeRate) && snapshot.feeRate >= 0 && snapshot.feeRate <= 65_535 && Number.isInteger(snapshot.protocolFeeRate) && snapshot.protocolFeeRate >= 0 && snapshot.protocolFeeRate <= 65_535 && /^[0-9a-f]{64}$/.test(snapshot.rawPayloadHash ?? "") && snapshot.tickArrays.every((array) => typeof array?.address === "string" && array.address && array.pool === snapshot.address && ["fixed", "dynamic"].includes(array.type) && Number.isInteger(array.startTickIndex) && Number.isInteger(array.initializedTickCount) && array.initializedTickCount >= 0 && array.initializedTickCount <= 88 && Array.isArray(array.initializedTicks) && array.initializedTickCount === array.initializedTicks.length && /^[0-9a-f]{64}$/.test(array.rawPayloadHash ?? "")) && completeOrcaTicks(snapshot);
  for (const [pool, row] of Object.entries(store.state.pools).sort(([left], [right]) => left.localeCompare(right))) if (row.protocol === "orca-whirlpool") { const snapshot = row.accountSnapshot, incomplete = snapshot && (snapshot.address !== pool || !completeOrcaQuoteEvidence(snapshot)); if (!snapshot || incomplete || stale(snapshot.observedAt)) jobs.push({ key: `orca-pool-snapshot:${pool}`, type: "orca_pool_snapshot", payload: { schemaVersion: 1, chain: CHAIN, pool, reason: !snapshot ? "missing" : incomplete ? "incomplete_quote_evidence" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: latestPoolDependencySlot(snapshot) } }); }
  const completeMeteoraEvidence = (snapshot) => completePersistedPoolEnvelope(snapshot) && snapshot?.programId === METEORA_DLMM_PROGRAM && snapshot.commitment === "finalized" && Number.isSafeInteger(snapshot.stateSlot) && Number.isSafeInteger(snapshot.binArraySlot) && Number.isSafeInteger(snapshot.balanceSlot) && snapshot.stateSlot <= snapshot.binArraySlot && snapshot.binArraySlot <= snapshot.balanceSlot && snapshot.binArrayCoverage === "finalized_program_account_snapshot" && Array.isArray(snapshot.rewardMints) && snapshot.rewardMints.length === 2 && snapshot.rewardMints.every((mint) => typeof mint === "string" && mint) && tokenPrograms.has(snapshot.tokenProgram0) && tokenPrograms.has(snapshot.tokenProgram1) && validateBoundPoolMintEvidence(snapshot, snapshot.balanceSlot) && Array.isArray(snapshot.binArrays) && snapshot.binArrays.length <= 13_312 && new Set(snapshot.binArrays.map((array) => array?.address)).size === snapshot.binArrays.length && new Set(snapshot.binArrays.map((array) => array?.index)).size === snapshot.binArrays.length && snapshot.binArrays.every((array) => typeof array?.address === "string" && array.address && array.pool === snapshot.address && Number.isInteger(array.index) && array.initializedBinCount === 70 && Number.isInteger(array.occupiedBinCount) && array.occupiedBinCount >= 0 && array.occupiedBinCount <= 70 && Array.isArray(array.bins) && array.bins.length === 70 && array.bins.every((bin, offset) => bin?.binId === array.index * 70 + offset) && /^[0-9a-f]{64}$/.test(array.rawPayloadHash ?? "")) && completeMeteoraBitmapExtension(snapshot) && /^[0-9a-f]{64}$/.test(snapshot.rawPayloadHash ?? "");
  for (const [pool, row] of Object.entries(store.state.pools).sort(([left], [right]) => left.localeCompare(right))) if (row.protocol === "meteora-dlmm") { const snapshot = row.accountSnapshot, incomplete = snapshot && (snapshot.address !== pool || !completeMeteoraEvidence(snapshot)); if (!snapshot || incomplete || stale(snapshot.observedAt)) jobs.push({ key: `meteora-dlmm-pool-snapshot:${pool}`, type: "meteora_dlmm_pool_snapshot", payload: { schemaVersion: 1, chain: CHAIN, pool, reason: !snapshot ? "missing" : incomplete ? "incomplete_pool_evidence" : "stale", canonicalAsOf: new Date(now).toISOString(), sourceSlot: latestPoolDependencySlot(snapshot) } }); }
  return { candidates, security, jobs };
}

export function compileWarehouseMetadataSql(state, sequence, projections = { candidates: [], security: [], jobs: [] }) {
  if (!canonicalAggregateProjections(state)) throw new Error("invalid persisted aggregate projections");
  if (!state?.mints || typeof state.mints !== "object" || Array.isArray(state.mints)) throw new Error("invalid warehouse mint state"); checkpointSql(sequence);
  const rows = Object.entries(state.mints).sort(([left], [right]) => left.localeCompare(right)).map(([mint, row]) => { const projected = warehouseTokenProjection(state, mint, row); return `(${sqlLiteral(CHAIN)}, ${sqlLiteral(mint)}, ${projected.decimals ?? "NULL"}, ${jsonbLiteral(projected.metadata)}, ${jsonbLiteral(projected.authorities)}, ${jsonbLiteral(projected.extensions)}, ${projected.sourceSlot ?? "NULL"}, ${sqlLiteral(projected.contentHash)})`; });
  const activeTokenMints = `ARRAY[${Object.keys(state.mints).sort().map(sqlLiteral).join(", ")}]::text[]`;
  if (!Array.isArray(projections?.candidates) || !Array.isArray(projections?.security) || !Array.isArray(projections?.jobs ?? [])) throw new Error("invalid warehouse projections");
  const candidateMints = new Set(), candidateRows = projections.candidates.map((row) => { if (!row.mint || row.scoreVersion !== "activity-v1" || candidateMints.has(row.mint) || !Number.isSafeInteger(row.score) || !["review_required", "eligible", "rejected"].includes(row.state)) throw new Error("invalid warehouse candidate row"); candidateMints.add(row.mint); const contentHash = projectionContentHash("warehouse-candidate-v1", { scoreVersion: row.scoreVersion, evidence: row.evidence, score: row.score, state: row.state }); return `(${sqlLiteral(CHAIN)}, ${sqlLiteral(row.mint)}, ${sqlLiteral(row.scoreVersion)}, ${jsonbLiteral(row.evidence)}, ${row.score}, ${sqlLiteral(row.state)}, ${sqlLiteral(contentHash)})`; });
  const activeCandidateMints = `ARRAY[${[...candidateMints].map(sqlLiteral).join(", ")}]::text[]`;
  const securityRows = projections.security.map((row) => { const observed = parseCanonicalUtcTimestamp(row.observedAt), expires = parseCanonicalUtcTimestamp(row.expiresAt); if (!row.mint || !row.ruleVersion || !Number.isSafeInteger(row.sourceSlot) || row.sourceSlot < 0 || !["unknown", "low", "medium", "high"].includes(row.severity) || typeof row.blocksResearch !== "boolean" || typeof row.blocksEntry !== "boolean" || typeof row.blocksExit !== "boolean" || observed == null || expires == null || expires <= observed) throw new Error("invalid warehouse security row"); return `(${sqlLiteral(CHAIN)}, ${sqlLiteral(row.mint)}, ${sqlLiteral(row.ruleVersion)}, ${row.sourceSlot}, NULL, ${jsonbLiteral(row.evidence)}, ${sqlLiteral(row.severity)}, ${row.blocksResearch}, ${row.blocksEntry}, ${row.blocksExit}, ${sqlLiteral(row.observedAt)}, ${sqlLiteral(row.expiresAt)})`; });
  const jobRows = (projections.jobs ?? []).map((row) => { if (!/^[a-z0-9_-]+:[^\u0000-\u001f]+$/.test(row.key ?? "") || !["account_snapshot", "cpmm_pool_snapshot", "amm_v4_pool_snapshot", "pump_swap_pool_snapshot", "pump_bonding_curve_snapshot", "clmm_pool_snapshot", "orca_pool_snapshot", "meteora_dlmm_pool_snapshot", "offchain_metadata_snapshot"].includes(row.type) || row.payload?.schemaVersion !== 1 || row.payload?.chain !== CHAIN) throw new Error("invalid warehouse operational job"); return `(${sqlLiteral(row.key)}, ${sqlLiteral(row.type)}, ${jsonbLiteral(row.payload)}, 'pending', 0, now())`; });
  const activeJobKeys = `ARRAY[${(projections.jobs ?? []).map((row) => sqlLiteral(row.key)).join(", ")}]::text[]`;
  return `BEGIN;\nDELETE FROM tokens WHERE chain = ${sqlLiteral(CHAIN)} AND NOT (mint = ANY(${activeTokenMints}));\nDELETE FROM candidates WHERE chain = ${sqlLiteral(CHAIN)} AND score_version = 'activity-v1' AND NOT (mint = ANY(${activeCandidateMints}));\n${rows.length ? `INSERT INTO tokens (chain, mint, decimals, metadata, authorities, extensions, source_slot, content_hash) VALUES\n${rows.join(",\n")}\nON CONFLICT (chain, mint) DO UPDATE SET decimals = EXCLUDED.decimals, metadata = EXCLUDED.metadata, authorities = EXCLUDED.authorities, extensions = EXCLUDED.extensions, source_slot = EXCLUDED.source_slot, content_hash = EXCLUDED.content_hash, updated_at = now();\n` : ""}${candidateRows.length ? `INSERT INTO candidates (chain, mint, score_version, evidence_snapshot, score, state, content_hash) VALUES\n${candidateRows.join(",\n")}\nON CONFLICT (chain, mint, score_version) DO UPDATE SET evidence_snapshot = EXCLUDED.evidence_snapshot, score = EXCLUDED.score, state = EXCLUDED.state, content_hash = EXCLUDED.content_hash, updated_at = now();\n` : ""}${securityRows.length ? `INSERT INTO security_snapshots (chain, mint, rule_version, source_slot, source_signature, evidence, severity, blocks_research, blocks_entry, blocks_exit, observed_at, expires_at) VALUES\n${securityRows.join(",\n")}\nON CONFLICT (chain, mint, rule_version, source_slot) WHERE source_slot IS NOT NULL DO UPDATE SET evidence = EXCLUDED.evidence, severity = EXCLUDED.severity, blocks_research = EXCLUDED.blocks_research, blocks_entry = EXCLUDED.blocks_entry, blocks_exit = EXCLUDED.blocks_exit, observed_at = EXCLUDED.observed_at, expires_at = EXCLUDED.expires_at;\n` : ""}UPDATE operational_jobs SET status = 'cancelled', updated_at = now() WHERE job_type IN ('account_snapshot', 'cpmm_pool_snapshot', 'amm_v4_pool_snapshot', 'pump_swap_pool_snapshot', 'pump_bonding_curve_snapshot', 'clmm_pool_snapshot', 'orca_pool_snapshot', 'meteora_dlmm_pool_snapshot', 'offchain_metadata_snapshot') AND status = 'pending' AND NOT (job_key = ANY(${activeJobKeys}));\n${jobRows.length ? `INSERT INTO operational_jobs (job_key, job_type, payload, status, attempts, available_at) VALUES\n${jobRows.join(",\n")}\nON CONFLICT (job_key) WHERE job_key IS NOT NULL DO UPDATE SET job_type = CASE WHEN operational_jobs.status = 'running' THEN operational_jobs.job_type ELSE EXCLUDED.job_type END, payload = CASE WHEN operational_jobs.status = 'running' THEN operational_jobs.payload ELSE EXCLUDED.payload END, status = CASE WHEN operational_jobs.status = 'running' THEN operational_jobs.status ELSE 'pending' END, attempts = CASE WHEN operational_jobs.status = 'running' THEN operational_jobs.attempts ELSE 0 END, available_at = CASE WHEN operational_jobs.status = 'running' THEN operational_jobs.available_at ELSE now() END, updated_at = now();\n` : ""}${checkpointSql(sequence)}COMMIT;\n`;
}

const WAREHOUSE_RECONCILIATION_KEYS = ["events", "instructions", "swaps", "balanceChanges", "nativeTransfers", "deadLetters", "tokens", "candidates", "pools"];

function validWarehouseReconciliationEnvelope(reconciliation, sequence) {
  return reconciliation?.schemaVersion === 7 && reconciliation.verified === true && reconciliation.sequence === sequence && reconciliation.events === sequence && WAREHOUSE_RECONCILIATION_KEYS.every((key) => Number.isSafeInteger(reconciliation[key]) && reconciliation[key] >= 0) && /^[0-9a-f]{64}$/.test(reconciliation.clickhouseIdentityDigest ?? "") && /^[0-9a-f]{64}$/.test(reconciliation.clickhouseContentDigest ?? "") && /^[0-9a-f]{32}$/.test(reconciliation.postgresIdentityDigest ?? "") && /^[0-9a-f]{32}$/.test(reconciliation.postgresContentDigest ?? "") && /^[0-9a-f]{40}$/.test(reconciliation.redisIdentityDigest ?? "") && /^[0-9a-f]{40}$/.test(reconciliation.redisTokenContentDigest ?? "") && /^[0-9a-f]{40}$/.test(reconciliation.redisPoolContentDigest ?? "") && /^[0-9a-f]{40}$/.test(reconciliation.redisStatsContentDigest ?? "");
}

export function assessWarehouseCheckpoint(checkpoint, eventSequence, oldestSequence, staleAfterMs = 300_000, maxLagEvents = 1_000, now = Date.now()) {
  const unavailable = (reason) => ({ available: false, healthy: false, reason, sequence: null, eventSequence, lagEvents: null, ageMs: null, staleAfterMs, maxLagEvents });
  if (!checkpoint) return unavailable("checkpoint_unavailable");
  const updated = parseCanonicalUtcTimestamp(checkpoint.updatedAt), sequence = Number(checkpoint.lastSequence);
  if (checkpoint.schemaVersion !== 2 || checkpoint.consumer !== "warehouse-canonical-events" || !Number.isSafeInteger(sequence) || sequence < 0 || !Number.isSafeInteger(eventSequence) || eventSequence < 0 || !Number.isSafeInteger(oldestSequence) || oldestSequence < 1 || updated == null) return unavailable("checkpoint_invalid");
  if (checkpoint.chain !== CHAIN || checkpoint.genesisHash !== GENESIS_HASH) return { ...unavailable("checkpoint_network_mismatch"), sequence };
  const sinks = checkpoint.sinks;
  if (!sinks || ![sinks.clickhouse, sinks.postgres, sinks.redis].every((value) => Number.isSafeInteger(value) && value >= 0)) return { ...unavailable("sink_evidence_unavailable"), sequence };
  if ([sinks.clickhouse, sinks.postgres, sinks.redis].some((value) => value !== sequence)) return { ...unavailable("sink_sequence_mismatch"), sequence, sinks };
  const reconciliation = checkpoint.reconciliation; if (!validWarehouseReconciliationEnvelope(reconciliation, sequence)) return { ...unavailable("content_reconciliation_unavailable"), sequence, sinks };
  if (sequence > eventSequence) return { ...unavailable("checkpoint_ahead_of_index"), sequence };
  const lagEvents = eventSequence - sequence, ageMs = now - updated, replayHistoryLost = sequence < oldestSequence - 1, reason = ageMs < 0 ? "checkpoint_clock_skew" : replayHistoryLost ? "checkpoint_behind_replay_history" : lagEvents > maxLagEvents ? "warehouse_lag_exceeded" : ageMs > staleAfterMs ? "warehouse_checkpoint_stale" : null;
  return { available: true, healthy: reason == null, reason, chain: checkpoint.chain, genesisHash: checkpoint.genesisHash, sequence, eventSequence, oldestSequence, lagEvents, ageMs, staleAfterMs, maxLagEvents, replayHistoryLost, sinks, reconciliation };
}

function runProcess(command, args, input, spawnProcess = spawn, env = process.env) {
  return runBoundedProcess({ command, args, input, spawnProcess, env, label: `${command} warehouse sync` });
}

function captureProcess(command, args, spawnProcess = spawn, env = process.env) {
  return runBoundedProcess({ command, args, spawnProcess, env, stdoutBytes: 1_024, label: `${command} warehouse probe` });
}

export function validateWarehouseSinkSequences(expectedSequence, values) {
  if (!Number.isSafeInteger(expectedSequence) || expectedSequence < 0) throw new Error("invalid expected warehouse sequence");
  const postgres = String(values?.postgres ?? "").trim().split(/\r?\n/);
  if (postgres.length !== 3 || !/^\d+$/.test(postgres[0])) throw new Error("postgres warehouse sequence unavailable");
  if (postgres[1] !== CHAIN || postgres[2] !== GENESIS_HASH) throw new Error("postgres warehouse network identity mismatch");
  const sinks = { postgres: Number(postgres[0]) };
  for (const name of ["clickhouse", "redis"]) { const text = String(values?.[name] ?? "").trim(); if (!/^\d+$/.test(text)) throw new Error(`${name} warehouse sequence unavailable`); const sequence = Number(text); if (!Number.isSafeInteger(sequence) || sequence !== expectedSequence) throw new Error(`${name} warehouse sequence mismatch`); sinks[name] = sequence; }
  if (!Number.isSafeInteger(sinks.postgres) || sinks.postgres !== expectedSequence) throw new Error("postgres warehouse sequence mismatch");
  return { clickhouse: sinks.clickhouse, postgres: sinks.postgres, redis: sinks.redis };
}

function digestIdentities(algorithm, identities) { return crypto.createHash(algorithm).update([...identities].sort().join("\n")).digest("hex"); }
export function expectedWarehouseReconciliation(state, sequence, projections, facts) {
  if (!Number.isSafeInteger(sequence) || sequence < 0 || !state?.mints || typeof state.mints !== "object" || Array.isArray(state.mints) || !state?.pools || typeof state.pools !== "object" || Array.isArray(state.pools) || !Array.isArray(projections?.candidates) || !facts || ![facts.instructions, facts.swaps, facts.balanceChanges, facts.nativeTransfers, facts.deadLetters].every(Array.isArray) || [facts.instructions, facts.swaps, facts.balanceChanges, facts.nativeTransfers, facts.deadLetters].some((rows) => rows.some((row) => !/^[0-9a-f]{64}$/.test(row?.content_hash ?? "")))) throw new Error("invalid warehouse reconciliation state");
  if (facts.instructions.some((row) => typeof row?.event_id !== "string" || !row.event_id) || facts.swaps.some((row) => typeof row?.swap_id !== "string" || !row.swap_id) || facts.balanceChanges.some((row) => typeof row?.signature !== "string" || !row.signature || !Number.isSafeInteger(row.account_index) || row.account_index < 0) || facts.nativeTransfers.some((row) => typeof row?.transfer_id !== "string" || !row.transfer_id) || facts.deadLetters.some((row) => typeof row?.identity !== "string" || !row.identity)) throw new Error("invalid warehouse reconciliation identity");
  const clickhouseIdentities = [...facts.instructions.map((row) => `instruction:${row.event_id}`), ...facts.swaps.map((row) => `swap:${row.swap_id}`), ...facts.balanceChanges.map((row) => `balance:${row.signature}:${row.account_index}`), ...facts.nativeTransfers.map((row) => `native:${row.transfer_id}`), ...facts.deadLetters.map((row) => `dead-letter:${row.identity}`)], clickhouseContentIdentities = [...facts.instructions.map((row) => `instruction:${row.event_id}:${row.content_hash}`), ...facts.swaps.map((row) => `swap:${row.swap_id}:${row.content_hash}`), ...facts.balanceChanges.map((row) => `balance:${row.signature}:${row.account_index}:${row.content_hash}`), ...facts.nativeTransfers.map((row) => `native:${row.transfer_id}:${row.content_hash}`), ...facts.deadLetters.map((row) => `dead-letter:${row.identity}:${row.content_hash}`)];
  if (projections.candidates.some((row) => typeof row?.mint !== "string" || !row.mint)) throw new Error("invalid warehouse reconciliation identity");
  const postgresIdentities = [...Object.keys(state.mints).map((mint) => `token:${mint}`), ...projections.candidates.map((row) => `candidate:${row.mint}`)], postgresContentIdentities = [...Object.entries(state.mints).map(([mint, row]) => `token:${mint}:${warehouseTokenProjection(state, mint, row).contentHash}`), ...projections.candidates.map((row) => `candidate:${row.mint}:${projectionContentHash("warehouse-candidate-v1", { scoreVersion: row.scoreVersion, evidence: row.evidence, score: row.score, state: row.state })}`)], redisIdentities = [...Object.keys(state.pools).map((pool) => `pool:${pool}`), ...Object.keys(state.mints).map((mint) => `token:${mint}`)], redisTokenContents = Object.entries(state.mints).map(([mint, row]) => `${mint}:${redisJson(redisHotTokenRow(state, mint, row), "mint")}`), redisPoolContents = Object.entries(state.pools).map(([pool, row]) => `${pool}:${redisJson(row, "pool")}`);
  return { sequence, events: sequence, instructions: facts.instructions.length, swaps: facts.swaps.length, balanceChanges: facts.balanceChanges.length, nativeTransfers: facts.nativeTransfers.length, deadLetters: facts.deadLetters.length, tokens: Object.keys(state.mints).length, candidates: projections.candidates.length, pools: Object.keys(state.pools).length, clickhouseIdentityDigest: digestIdentities("sha256", clickhouseIdentities), clickhouseContentDigest: digestIdentities("sha256", clickhouseContentIdentities), postgresIdentityDigest: digestIdentities("md5", postgresIdentities), postgresContentDigest: digestIdentities("md5", postgresContentIdentities), redisIdentityDigest: digestIdentities("sha1", redisIdentities), redisTokenContentDigest: digestIdentities("sha1", redisTokenContents), redisPoolContentDigest: digestIdentities("sha1", redisPoolContents), redisStatsContentDigest: crypto.createHash("sha1").update(redisJson(redisHotStatsRow(state), "stats")).digest("hex") };
}

function numericLines(value, count, label) { const lines = String(value ?? "").trim().split(/\r?\n/), numbers = lines.map(Number); if (lines.length !== count || lines.some((line) => !/^\d+$/.test(line)) || numbers.some((number) => !Number.isSafeInteger(number))) throw new Error(`${label} reconciliation evidence unavailable`); return numbers; }
function reconciliationLines(value, count, label) { const lines = String(value ?? "").trim().split(/\r?\n/); if (lines.length !== count || lines.some((line) => !line)) throw new Error(`${label} reconciliation evidence unavailable`); return lines; }
export function validateWarehouseReconciliation(expected, values) {
  const keys = ["sequence", ...WAREHOUSE_RECONCILIATION_KEYS]; if (!expected || keys.some((key) => !Number.isSafeInteger(expected[key]) || expected[key] < 0) || !/^[0-9a-f]{64}$/.test(expected.clickhouseIdentityDigest ?? "") || !/^[0-9a-f]{64}$/.test(expected.clickhouseContentDigest ?? "") || !/^[0-9a-f]{32}$/.test(expected.postgresIdentityDigest ?? "") || !/^[0-9a-f]{32}$/.test(expected.postgresContentDigest ?? "") || !/^[0-9a-f]{40}$/.test(expected.redisIdentityDigest ?? "") || !/^[0-9a-f]{40}$/.test(expected.redisTokenContentDigest ?? "") || !/^[0-9a-f]{40}$/.test(expected.redisPoolContentDigest ?? "") || !/^[0-9a-f]{40}$/.test(expected.redisStatsContentDigest ?? "")) throw new Error("invalid expected warehouse reconciliation");
  const clickhouseLines = reconciliationLines(values?.clickhouse, 8, "clickhouse"), postgresLines = reconciliationLines(values?.postgres, 5, "postgres"), redisLines = reconciliationLines(values?.redis, 13, "redis"), clickhouse = numericLines(clickhouseLines.slice(0, 6).join("\n"), 6, "clickhouse"), postgres = numericLines(postgresLines.slice(0, 3).join("\n"), 3, "postgres"), redis = numericLines(redisLines.slice(0, 7).join("\n"), 7, "redis"), actual = { sequence: postgres[0], events: clickhouse[0], instructions: clickhouse[1], swaps: clickhouse[2], balanceChanges: clickhouse[3], nativeTransfers: clickhouse[4], deadLetters: clickhouse[5], tokens: postgres[1], candidates: postgres[2], pools: redis[1] };
  if (redis[0] !== expected.sequence || redis[2] !== expected.tokens || redis[3] !== 1 || redis[4] !== expected.sequence || redis[5] !== expected.pools || redis[6] !== expected.tokens || redisLines[7] !== CHAIN || redisLines[8] !== GENESIS_HASH || clickhouseLines[6] !== expected.clickhouseIdentityDigest || clickhouseLines[7] !== expected.clickhouseContentDigest || postgresLines[3] !== expected.postgresIdentityDigest || postgresLines[4] !== expected.postgresContentDigest || redisLines[9] !== expected.redisIdentityDigest || redisLines[10] !== expected.redisTokenContentDigest || redisLines[11] !== expected.redisPoolContentDigest || redisLines[12] !== expected.redisStatsContentDigest || keys.some((key) => actual[key] !== expected[key])) throw new Error("warehouse content reconciliation mismatch"); return { schemaVersion: 7, verified: true, ...expected };
}

export async function probeWarehouseReconciliation(expected, spawnProcess = spawn, env = process.env) {
  const [clickhouse, postgres, redis] = await Promise.all([
    captureProcess("clickhouse-client", ["--query", "SELECT toString(uniqExact(sequence)) FROM terminal_dex.canonical_events WHERE chain='solana-mainnet' UNION ALL SELECT toString(uniqExact(event_id)) FROM terminal_dex.canonical_instructions WHERE chain='solana-mainnet' UNION ALL SELECT toString(uniqExact(swap_id)) FROM terminal_dex.canonical_swaps WHERE chain='solana-mainnet' UNION ALL SELECT toString(uniqExact(tuple(signature, account_index))) FROM terminal_dex.canonical_balance_changes WHERE chain='solana-mainnet' UNION ALL SELECT toString(uniqExact(transfer_id)) FROM terminal_dex.canonical_native_transfers WHERE chain='solana-mainnet' UNION ALL SELECT toString(uniqExact(identity)) FROM terminal_dex.canonical_dead_letters WHERE chain='solana-mainnet' UNION ALL SELECT lower(hex(SHA256(arrayStringConcat(arraySort(groupArray(identity)), '\\n')))) FROM (SELECT concat('instruction:', event_id) AS identity FROM terminal_dex.canonical_instructions WHERE chain='solana-mainnet' UNION ALL SELECT concat('swap:', swap_id) FROM terminal_dex.canonical_swaps WHERE chain='solana-mainnet' UNION ALL SELECT concat('balance:', signature, ':', toString(account_index)) FROM terminal_dex.canonical_balance_changes WHERE chain='solana-mainnet' UNION ALL SELECT concat('native:', transfer_id) FROM terminal_dex.canonical_native_transfers WHERE chain='solana-mainnet' UNION ALL SELECT concat('dead-letter:', identity) FROM terminal_dex.canonical_dead_letters WHERE chain='solana-mainnet') UNION ALL SELECT lower(hex(SHA256(arrayStringConcat(arraySort(groupArray(identity)), '\\n')))) FROM (SELECT concat('instruction:', event_id, ':', content_hash) AS identity FROM terminal_dex.canonical_instructions WHERE chain='solana-mainnet' UNION ALL SELECT concat('swap:', swap_id, ':', content_hash) FROM terminal_dex.canonical_swaps WHERE chain='solana-mainnet' UNION ALL SELECT concat('balance:', signature, ':', toString(account_index), ':', content_hash) FROM terminal_dex.canonical_balance_changes WHERE chain='solana-mainnet' UNION ALL SELECT concat('native:', transfer_id, ':', content_hash) FROM terminal_dex.canonical_native_transfers WHERE chain='solana-mainnet' UNION ALL SELECT concat('dead-letter:', identity, ':', content_hash) FROM terminal_dex.canonical_dead_letters WHERE chain='solana-mainnet') FORMAT TabSeparatedRaw"], spawnProcess, env),
    captureProcess("psql", ["--no-psqlrc", "--set", "ON_ERROR_STOP=1", "--tuples-only", "--no-align", "--quiet", "--command", "SELECT COALESCE(cursor, '0') FROM ingestion_checkpoints WHERE consumer='warehouse-canonical-events'; SELECT count(*) FROM tokens WHERE chain='solana-mainnet'; SELECT count(*) FROM candidates WHERE chain='solana-mainnet' AND score_version='activity-v1'; SELECT md5(COALESCE(string_agg(identity, E'\\n' ORDER BY identity), '')) FROM (SELECT 'token:' || mint AS identity FROM tokens WHERE chain='solana-mainnet' UNION ALL SELECT 'candidate:' || mint FROM candidates WHERE chain='solana-mainnet' AND score_version='activity-v1') identities; SELECT md5(COALESCE(string_agg(identity, E'\\n' ORDER BY identity), '')) FROM (SELECT 'token:' || mint || ':' || COALESCE(content_hash, 'invalid') AS identity FROM tokens WHERE chain='solana-mainnet' UNION ALL SELECT 'candidate:' || mint || ':' || COALESCE(content_hash, 'invalid') FROM candidates WHERE chain='solana-mainnet' AND score_version='activity-v1') contents;"], spawnProcess, env),
    captureProcess("redis-cli", ["--raw", "EVAL", "local p='terminal_dex:hot:'..ARGV[1]; local s=redis.call('GET',p..':stats'); if not s then return {redis.call('GET','terminal_dex:hot:current') or '0',redis.call('HLEN',p..':pools'),redis.call('HLEN',p..':tokens'),0,0,0,0,'invalid','invalid','invalid','invalid','invalid','invalid'} end; local ok,v=pcall(cjson.decode,s); if not ok then return {'invalid'} end; local ids,tokenContents,poolContents={},{},{}; for _,k in ipairs(redis.call('HKEYS',p..':pools')) do table.insert(ids,'pool:'..k); table.insert(poolContents,k..':'..redis.call('HGET',p..':pools',k)) end; for _,k in ipairs(redis.call('HKEYS',p..':tokens')) do table.insert(ids,'token:'..k); table.insert(tokenContents,k..':'..redis.call('HGET',p..':tokens',k)) end; table.sort(ids); table.sort(tokenContents); table.sort(poolContents); return {redis.call('GET','terminal_dex:hot:current') or '0',redis.call('HLEN',p..':pools'),redis.call('HLEN',p..':tokens'),1,v.eventSequence or 'invalid',v.pools or 'invalid',v.tokens or 'invalid',v.chain or 'invalid',v.genesisHash or 'invalid',redis.sha1hex(table.concat(ids,'\\n')),redis.sha1hex(table.concat(tokenContents,'\\n')),redis.sha1hex(table.concat(poolContents,'\\n')),redis.sha1hex(s)}", "0", String(expected.sequence)], spawnProcess, env),
  ]);
  return validateWarehouseReconciliation(expected, { clickhouse, postgres, redis });
}

export async function probeWarehouseSinks(expectedSequence, spawnProcess = spawn, env = process.env) {
  const [clickhouse, postgres, redis] = await Promise.all([
    captureProcess("clickhouse-client", ["--query", "SELECT toString(ifNull(max(sequence), 0)) FROM terminal_dex.canonical_events WHERE chain='solana-mainnet' FORMAT TabSeparatedRaw"], spawnProcess, env),
    captureProcess("psql", ["--no-psqlrc", "--set", "ON_ERROR_STOP=1", "--tuples-only", "--no-align", "--quiet", "--command", "SELECT COALESCE(cursor, '') FROM ingestion_checkpoints WHERE consumer='warehouse-canonical-events'; SELECT chain FROM ingestion_checkpoints WHERE consumer='warehouse-canonical-events'; SELECT genesis_hash FROM ingestion_checkpoints WHERE consumer='warehouse-canonical-events'"], spawnProcess, env),
    captureProcess("redis-cli", ["--raw", "GET", "terminal_dex:hot:current"], spawnProcess, env),
  ]);
  return validateWarehouseSinkSequences(expectedSequence, { clickhouse, postgres, redis });
}

export async function syncWarehouseBatch(batch, spawnProcess = spawn, env = process.env, facts = null, postgresSql = checkpointSql(batch.toSequence), redisInput = null) {
  if (!Array.isArray(batch?.events) || !Number.isSafeInteger(batch.toSequence) || batch.toSequence < 0) throw new Error("invalid warehouse batch");
  if (facts && (!Array.isArray(facts.slots) || facts.slots.some((slot) => !Number.isSafeInteger(slot) || slot < 0) || !Array.isArray(facts.instructions) || !Array.isArray(facts.swaps) || !Array.isArray(facts.balanceChanges) || !Array.isArray(facts.nativeTransfers) || !Array.isArray(facts.deadLetters))) throw new Error("invalid warehouse facts");
  if (typeof postgresSql !== "string" || !postgresSql.trim()) throw new Error("invalid warehouse PostgreSQL transaction");
  if (redisInput != null && !Buffer.isBuffer(redisInput)) throw new Error("invalid Redis hot-state transaction");
  if (batch.events.length) { const body = `${batch.events.map((row) => JSON.stringify(row)).join("\n")}\n`; await runProcess("clickhouse-client", ["--query", "INSERT INTO terminal_dex.canonical_events FORMAT JSONEachRow"], body, spawnProcess, env); }
  if (facts) {
    const suffixes = [["canonical_instructions", facts.instructions], ["canonical_swaps", facts.swaps], ["canonical_balance_changes", facts.balanceChanges], ["canonical_native_transfers", facts.nativeTransfers]];
    if (facts.slots.length) for (const [table, rows] of suffixes) { const slotList = facts.slots.join(","); await runProcess("clickhouse-client", ["--multiquery", "--query", `ALTER TABLE terminal_dex.${table} DELETE WHERE chain = '${CHAIN}' AND slot IN (${slotList}) SETTINGS mutations_sync = 2`], "", spawnProcess, env); if (rows.length) await runProcess("clickhouse-client", ["--query", `INSERT INTO terminal_dex.${table} FORMAT JSONEachRow`], `${rows.map((row) => JSON.stringify(row)).join("\n")}\n`, spawnProcess, env); }
    await runProcess("clickhouse-client", ["--multiquery", "--query", `ALTER TABLE terminal_dex.canonical_dead_letters DELETE WHERE chain = '${CHAIN}' SETTINGS mutations_sync = 2`], "", spawnProcess, env); if (facts.deadLetters.length) await runProcess("clickhouse-client", ["--query", "INSERT INTO terminal_dex.canonical_dead_letters FORMAT JSONEachRow"], `${facts.deadLetters.map((row) => JSON.stringify(row)).join("\n")}\n`, spawnProcess, env);
    if (facts.candleKeys?.length) { const predicates = facts.candleKeys.map((row) => `(pool=${sqlLiteral(row.pool)} AND interval_seconds=${row.interval} AND bucket_start=${sqlLiteral(new Date(row.bucket * 1_000).toISOString())})`).join(" OR "); await runProcess("clickhouse-client", ["--multiquery", "--query", `ALTER TABLE terminal_dex.canonical_candles DELETE WHERE chain = '${CHAIN}' AND (${predicates}) SETTINGS mutations_sync = 2`], "", spawnProcess, env); if (facts.candles.length) await runProcess("clickhouse-client", ["--query", "INSERT INTO terminal_dex.canonical_candles FORMAT JSONEachRow"], `${facts.candles.map((row) => JSON.stringify(row)).join("\n")}\n`, spawnProcess, env); }
  }
  await runProcess("psql", ["--no-psqlrc", "--set", "ON_ERROR_STOP=1"], postgresSql, spawnProcess, env);
  if (redisInput) await runProcess("redis-cli", ["--pipe"], redisInput, spawnProcess, env);
  return { synced: batch.events.length, sequence: batch.toSequence };
}

export async function writeWarehouseCheckpoint(filename, sequence, sinks, reconciliation) {
  if (!Number.isSafeInteger(sequence) || sequence < 0 || !sinks || [sinks.clickhouse, sinks.postgres, sinks.redis].some((value) => value !== sequence)) throw new Error("warehouse checkpoint sink sequence mismatch"); if (!validWarehouseReconciliationEnvelope(reconciliation, sequence)) throw new Error("verified warehouse reconciliation is required"); await durableAtomicWrite(filename, `${JSON.stringify({ schemaVersion: 2, consumer: "warehouse-canonical-events", chain: CHAIN, genesisHash: GENESIS_HASH, lastSequence: sequence, sinks, reconciliation, updatedAt: new Date().toISOString() })}\n`);
}

export function assertWarehousePublicationState(store) { store.assertWritable(); const recovery = store.recoveryQuality(); if (!recovery.canonical || recovery.capacityExceeded) { const error = new Error(`warehouse publication refused: ${recovery.reason}`); error.code = "INDEX_RECOVERY_INVALID"; error.reason = recovery.reason; throw error; } return true; }

async function main() {
  const config = loadConfig(), checkpointFile = config.warehouseCheckpointFile, checkpoint = await readBoundedJsonFile(checkpointFile, { missing: { lastSequence: 0 } });
  if (checkpoint?.evidenceReadError) throw new Error(`warehouse checkpoint is unavailable: ${checkpoint.evidenceReadError}`);
  const holderExclusions = await loadHolderExclusions(config.holderExclusionsFile), store = new IndexStore(config.dataFile, config.maxTransactions, config.retentionSeconds, holderExclusions, null, 200, config.maxStateFileBytes); await store.load(); assertWarehousePublicationState(store);
  const clientEnv = { ...process.env }; if (config.clickhousePasswordFile) clientEnv.CLICKHOUSE_PASSWORD = await readSecretFile(config.clickhousePasswordFile, "CLICKHOUSE_PASSWORD_FILE"); if (config.redisPasswordFile) clientEnv.REDISCLI_AUTH = await readSecretFile(config.redisPasswordFile, "REDIS_PASSWORD_FILE");
  const state = store.state, batch = compileWarehouseBatch(state, checkpoint), facts = compileWarehouseFacts(state, batch), projections = compileWarehouseProjections(store, config.staleAfterMs), postgresSql = compileWarehouseMetadataSql(state, batch.toSequence, projections), redisInput = compileRedisHotSync(state, batch, config.redisHotTtlSeconds, config.redisHotMaxBytes), result = await syncWarehouseBatch(batch, spawn, clientEnv, facts, postgresSql, redisInput), sinks = await probeWarehouseSinks(result.sequence, spawn, clientEnv), reconciliation = await probeWarehouseReconciliation(expectedWarehouseReconciliation(state, result.sequence, projections, facts), spawn, clientEnv); await writeWarehouseCheckpoint(checkpointFile, result.sequence, sinks, reconciliation); console.log(JSON.stringify({ ...result, sinks, reconciliation, candidates: projections.candidates.length, securitySnapshots: projections.security.length, operationalJobs: projections.jobs.length, redisBytes: redisInput.length }));
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main().catch((error) => { console.error(error.message); process.exitCode = 1; });
